module Admin
  module Ci
    class VariablesController < ApplicationController
      @variables: untyped

      def show: () -> untyped

      def update: () -> untyped

      private

      def variables: () -> untyped

      def render_instance_variables: () -> untyped

      def render_error: (untyped errors) -> untyped

      def variables_params: () -> untyped

      def variable_params_attributes: () -> ::Array[:id | :variable_type | :key | :description | :value | :protected | :masked | :hidden | :raw | :_destroy]
    end
  end
end
