class AccessTokenValidationService
  @token: untyped

  @request: untyped

  # Results:
  VALID: :valid

  EXPIRED: :expired

  REVOKED: :revoked

  INSUFFICIENT_SCOPE: :insufficient_scope

  IMPERSONATION_DISABLED: :impersonation_disabled

  attr_reader token: untyped

  attr_reader request: untyped

  def initialize: (untyped token, ?request: untyped?) -> void

  def validate: (?scopes: untyped) -> untyped

  # True if the token's scope contains any of the passed scopes.
  def include_any_scope?: (untyped required_scopes) -> (false | untyped)
end
