class NoteSummary
  @note: untyped

  @metadata: untyped

  attr_reader note: untyped

  attr_reader metadata: untyped

  def initialize: (untyped noteable, untyped project, untyped author, untyped body, ?action: untyped?, ?commit_count: untyped?, ?created_at: untyped?) -> void

  def metadata?: () -> untyped

  def set_commit_params: () -> untyped
end
