module Gitlab
  module Metrics
    module Lfs
      include Gitlab::Metrics::SliConfig

      def self.initialize_slis!: () -> untyped

      def self.update_objects_error_rate: () -> untyped

      def self.check_objects_error_rate: () -> untyped

      def self.validate_link_objects_error_rate: () -> untyped
    end
  end
end
