module Gitlab
  module Metrics
    # Rack middleware for tracking Rails and Grape requests.
    class RackMiddleware
      @app: untyped

      def initialize: (untyped app) -> void

      # env - A Hash containing Rack environment details.
      def call: (untyped env) -> untyped
    end
  end
end
