# frozen_string_literal: true
module Security
  module WeakPasswords
    # These words are predictable in GitLab's specific context, and
    # therefore cannot occur anywhere within a password.
    FORBIDDEN_WORDS: untyped

    # Substrings shorter than this may appear legitimately in a truly
    # random password.
    MINIMUM_SUBSTRING_SIZE: 4

    # Passwords of 64+ characters are more likely to randomly include a
    # forbidden substring.
    #
    # This length was chosen somewhat arbitrarily, balancing security,
    # usability, and skipping checks on `::User.random_password` which
    # is 128 chars. See https://gitlab.com/gitlab-org/gitlab/-/merge_requests/105755
    PASSWORD_SUBSTRING_CHECK_MAX_LENGTH: 64

    # Returns true when the password is on a list of weak passwords,
    # or contains predictable substrings derived from user attributes.
    # Case insensitive.
    def self.weak_for_user?: (untyped password, untyped user) -> untyped

    def self.user_info_in_password?: (untyped password, untyped user) -> untyped

    def self.common_phrases_in_password?: (untyped password) -> untyped

    private

    def self.forbidden_word_appears_in_password?: (untyped password) -> untyped

    def self.name_appears_in_password?: (untyped password, untyped user) -> (false | untyped)

    def self.username_appears_in_password?: (untyped password, untyped user) -> (false | untyped)

    def self.email_appears_in_password?: (untyped password, untyped user) -> (false | untyped)

    def self.password_on_weak_list?: (untyped password) -> untyped

    # Case-insensitively checks whether a password includes a dynamic
    # list of substrings. Substrings which are too short are not
    # predictable and may occur randomly, and therefore not checked.
    # Similarly passwords which are long enough to inadvertently and
    # randomly include a substring are not checked.
    def self.contains_predicatable_substring?: (untyped password, untyped substrings) -> (nil | untyped)
  end
end
