# This module has the necessary methods to show
# sprites or images next to the menu item.
module Sidebars
  module Concerns
    module HasIcon
      def sprite_icon: () -> nil

      def sprite_icon_html_options: () -> ::Hash[untyped, untyped]

      def image_path: () -> nil

      def icon_or_image?: () -> untyped
    end
  end
end
