module Sidebars
  module Concerns
    module LinkWithHtmlOptions
      # add on specific items as the pertain to `link_to` objects specifically
      def link_html_options: () -> untyped
    end
  end
end
