module Namespaces
  module TransferWorkerHelper
    extend ActiveSupport::Concern

    private

    def cancel_stale_transfer_state: (untyped namespace, **untyped log_params) -> (nil | untyped)
  end
end
