module ErrorTracking
  class SentryClient
    module Projects
      def projects: () -> untyped

      private

      def get_projects: () -> untyped

      def map_to_projects: (untyped projects) -> untyped

      def map_to_project: (untyped project) -> untyped
    end
  end
end
