module Clusters
  module Kubernetes
    class CreateOrUpdateServiceAccountService
      @kubeclient: untyped

      @service_account_name: untyped

      @service_account_namespace: untyped

      @service_account_namespace_labels: untyped

      @token_name: untyped

      @rbac: untyped

      @namespace_creator: untyped

      @role_binding_name: untyped

      def initialize: (untyped kubeclient, service_account_name: untyped, service_account_namespace: untyped, token_name: untyped, rbac: untyped, ?service_account_namespace_labels: untyped?, ?namespace_creator: bool, ?role_binding_name: untyped?) -> void

      def self.gitlab_creator: (untyped kubeclient, rbac: untyped) -> untyped

      def self.namespace_creator: (untyped kubeclient, service_account_name: untyped, service_account_namespace: untyped, service_account_namespace_labels: untyped, rbac: untyped) -> untyped

      def execute: () -> (nil | untyped)

      private

      attr_reader kubeclient: untyped

      attr_reader service_account_name: untyped

      attr_reader service_account_namespace: untyped

      attr_reader service_account_namespace_labels: untyped

      attr_reader token_name: untyped

      attr_reader rbac: untyped

      attr_reader namespace_creator: untyped

      attr_reader role_binding_name: untyped

      def ensure_project_namespace_exists: () -> untyped

      def create_role_or_cluster_role_binding: () -> untyped

      def create_or_update_knative_serving_role: () -> untyped

      def create_or_update_knative_serving_role_binding: () -> untyped

      def create_or_update_crossplane_database_role: () -> untyped

      def create_or_update_crossplane_database_role_binding: () -> untyped

      def service_account_resource: () -> untyped

      def service_account_token_resource: () -> untyped

      def cluster_role_binding_resource: () -> untyped

      def role_binding_resource: () -> untyped

      def knative_serving_role_resource: () -> untyped

      def knative_serving_role_binding_resource: () -> untyped

      def crossplane_database_role_resource: () -> untyped

      def crossplane_database_role_binding_resource: () -> untyped
    end
  end
end
