module Organizations
  class ProjectsController < ApplicationController
    @project: untyped

    def edit: () -> nil

    private

    def project: () -> untyped

    def authorize_project_view_edit_page!: () -> (untyped | nil)

    def safe_params: () -> untyped
  end
end
