module Branches
  class DeleteService < BaseService
    def execute: (untyped branch_name) -> untyped

    private

    def missing_branch_error: () -> untyped

    def unlock_artifacts: (untyped branch_name) -> untyped
  end
end
