class Projects::BadgesController < Projects::ApplicationController
  def pipeline: () -> untyped

  def coverage: () -> untyped

  def release: () -> untyped

  def custom: () -> untyped

  private

  def badge_layout: () -> untyped

  def render_badge: (untyped badge) -> untyped
end
