class Projects::ClustersController < ::Clusters::ClustersController
  @clusterable: untyped

  @project: untyped

  @repository: untyped

  private

  def clusterable: () -> untyped

  def project: () -> untyped

  def repository: () -> untyped
end
