class Projects::FeatureFlagsClientsController < Projects::ApplicationController
  def reset_token: () -> untyped

  private

  def feature_flags_client: () -> untyped

  def feature_flags_client_token_json: () -> untyped
end
