class Projects::FeatureFlagsUserListsController < Projects::ApplicationController
  @user_list: untyped

  def index: () -> nil

  def new: () -> nil

  def edit: () -> nil

  def show: () -> nil

  private

  def user_list: () -> untyped
end
