class Projects::GroupLinksController < Projects::ApplicationController
  def update: () -> untyped

  def destroy: () -> untyped

  def group_link: () -> untyped

  def group_link_params: () -> untyped
end
