class Projects::MattermostsController < Projects::ApplicationController
  @teams: untyped

  @teams_error_message: untyped

  @integration: untyped

  include Ci::TriggersHelper

  include ActionView::Helpers::AssetUrlHelper

  def new: () -> nil

  def create: () -> (nil | untyped)

  private

  def configure_params: () -> untyped

  def teams: () -> untyped

  def integration: () -> untyped
end
