class Projects::RunnersController < Projects::ApplicationController
  @runner: untyped

  def index: () -> untyped

  def edit: () -> nil

  def new: () -> nil

  def register: () -> (untyped | nil)

  def destroy: () -> untyped

  def resume: () -> untyped

  def pause: () -> untyped

  def show: () -> nil

  def toggle_shared_runners: () -> untyped

  def toggle_group_runners: () -> untyped

  def runner: () -> untyped

  def runner_update_service: () -> untyped

  def authorize_runner!: (untyped ability) -> (untyped | nil)
end
