class Projects::VariablesController < Projects::ApplicationController
  def show: () -> untyped

  def update: () -> untyped

  private

  def render_variables: () -> untyped

  def render_error: () -> untyped

  def variables_params: () -> untyped

  def variable_params_attributes: () -> ::Array[:id | :variable_type | :key | :description | :value | :protected | :masked | :hidden | :raw | :environment_scope | :_destroy]
end
