# Deprecated:
#   Remove with PrometheusIntegration mutations during any major release.
module Types
  module AlertManagement
    class PrometheusIntegrationType < ::Types::BaseObject
    end
  end
end
