module Members
  module InviteModalActions
    extend ActiveSupport::Concern

    def invite_search: () -> untyped

    private

    def invite_search_per_page: () -> untyped

    def invite_search_params: () -> untyped
  end
end
