module Gitlab
  module Ci
    class Config
      module Interpolation
        module Functions
          class ExpandVars < Base
            def self.function_expression_pattern: () -> ::Regexp

            def self.name: () -> "expand_vars"

            def execute: (untyped input_value) -> untyped
          end
        end
      end
    end
  end
end
