module Resolvers
  module Clusters
    class AgentActivityEventsResolver < BaseResolver
      alias agent object

      def resolve: (**untyped args) -> untyped

      private

      def can_view_activity_events?: () -> untyped
    end
  end
end
