module Enums
  class PackageMetadata
    ADVISORY_SOURCES: untyped

    DATA_TYPES: untyped

    VERSION_FORMATS: untyped

    def self.advisory_sources: () -> untyped

    def self.data_types: () -> untyped

    def self.version_formats: () -> untyped
  end
end
