module Gitlab
  module Ci
    module Parsers
      module Coverage
        class Cobertura
          InvalidXMLError: untyped

          InvalidLineInformationError: untyped

          def parse!: (untyped xml_data, untyped coverage_report, ?project_path: untyped?, ?worktree_paths: untyped?, **untyped _kwargs) -> untyped
        end
      end
    end
  end
end
