module Projects
  module Ml
    class CandidatesController < ApplicationController
      @experiment: untyped

      @candidate: untyped

      def show: () -> nil

      def promote: () -> nil

      def destroy: () -> untyped

      private

      def set_candidate: () -> untyped

      def check_read: () -> (untyped | nil)

      def check_write: () -> (untyped | nil)
    end
  end
end
