class DeviseMailerPreview < ActionMailer::Preview
  def confirmation_instructions_for_signup: () -> untyped

  def confirmation_instructions_for_new_email: () -> untyped

  def confirmation_instructions_for_secondary_email: () -> untyped

  def reset_password_instructions: () -> untyped

  def unlock_instructions: () -> untyped

  def password_change: () -> untyped

  def user_admin_approval: () -> untyped

  def email_changed: () -> untyped

  private

  def unsaved_user: () -> untyped
end
