module Gitlab
  module Doctor
    class Secrets
      @logger: untyped

      @all_models: untyped

      attr_reader logger: untyped

      def initialize: (untyped logger) -> void

      def run!: () -> untyped

      private

      # Skipping initializers may be needed if those attempt to access
      # encrypted data on initialization and could fail because of it.
      #
      # format example:
      # {
      #   model_class => {
      #     [
      #       { action: :create, filters: [:before, :filter_name1] },
      #       { action: :update, filters: [:after,  :filter_name2] }
      #     ]
      #   }
      # }
      MODEL_INITIALIZERS_TO_SKIP: ::Hash[untyped, ::Array[{ action: :initialize, filters: ::Array[:after | :initialize_properties] }]]

      def check_model_attributes: (untyped models_with_attributes) -> untyped

      def output_failures_for_model: (untyped model, untyped failures) -> untyped

      def models_with_encrypted_attributes: () -> untyped

      def models_with_attr_encrypted_attributes: () -> untyped

      def models_with_encrypted_tokens: () -> untyped

      def all_models: () -> untyped

      def valid_attribute?: (untyped data, untyped attr) -> untyped

      # WARNING: using this logic in other places than a Rake task will need a
      # different approach, as simply setting the callback again is not thread-safe
      def with_skipped_callbacks_for: (untyped model) { () -> untyped } -> untyped

      def skip_callbacks_for_model: (untyped model, ?reset: bool) -> untyped
    end
  end
end
