module RapidDiffs
  module Viewers
    module Text
      class TextViewComponent < ViewerComponent
        @virtual_rendering_params: untyped

        def virtual_rendering_params: () -> untyped
      end
    end
  end
end
