class MergeRequest::MetricsFinder
  @current_user: untyped

  @params: untyped

  include Gitlab::Allowable

  def initialize: (untyped current_user, ?::Hash[untyped, untyped] params) -> void

  def execute: () -> untyped

  private

  attr_reader current_user: untyped

  attr_reader params: untyped

  def by_target_project: (untyped items) -> untyped

  def by_merged_after: (untyped items) -> untyped

  def by_merged_before: (untyped items) -> untyped

  def user_not_authorized?: () -> untyped

  def init_collection: () -> untyped

  def klass: () -> untyped

  def target_project: () -> untyped

  def merged_after: () -> untyped

  def merged_before: () -> untyped
end
