module Gitlab
  module Checks
    class BaseSingleChecker < BaseChecker
      @change_access: untyped

      attr_reader change_access: untyped

      def initialize: (untyped change_access) -> void

      private

      def creation?: () -> untyped

      def deletion?: () -> untyped

      def update?: () -> untyped

      def tag_exists?: () -> untyped

      # If a commit is created from Web and signed by GitLab, we can skip the committer check because it's equal to
      # GitLab <noreply@gitlab.com>
      def signed_by_gitlab?: (untyped commit) -> (false | untyped)

      def commit_signatures: () -> untyped
    end
  end
end
