module Gitlab
  module Checks
    class LfsCheck < BaseBulkChecker
      LOG_MESSAGE: "Scanning repository for blobs stored in LFS and verifying their files have been uploaded to GitLab..."

      ERROR_MESSAGE: "LFS objects are missing. Ensure LFS is properly set up or try a manual \"git lfs push --all\"."

      def validate!: () -> (nil | untyped)
    end
  end
end
