module Ci
  module Preloaders
    class CommitStatusPreloader
      @statuses: untyped

      CLASSES: ::Array[untyped]

      def initialize: (untyped statuses) -> void

      def execute: (untyped relations) -> untyped

      private

      def objects: (untyped klass) -> untyped

      def associations: (untyped klass, untyped relations) -> untyped
    end
  end
end
