module ContainerRegistry
  class Referrer
    @artifact_type: untyped

    @digest: untyped

    @tag: untyped

    attr_reader artifact_type: untyped

    attr_reader digest: untyped

    attr_reader tag: untyped

    def initialize: (untyped artifact_type, untyped digest, untyped tag) -> void
  end
end
