module ContainerRegistry
  class Registry
    @uri: untyped

    @options: untyped

    @path: untyped

    @client: untyped

    @gitlab_api_client: untyped

    attr_reader uri: untyped

    attr_reader client: untyped

    attr_reader gitlab_api_client: untyped

    attr_reader path: untyped

    def initialize: (untyped uri, ?::Hash[untyped, untyped] options) -> void

    private

    def default_path: () -> untyped
  end
end
