module Projects
  module Pipelines
    class StagesController < Projects::Pipelines::ApplicationController
      @stage: untyped

      def play_manual: () -> untyped

      private

      def stage: () -> untyped
    end
  end
end
