module WebIde
  module Settings
    class ExtensionMarketplaceMetadataValidator
      include Messages

      # @param [Hash] context
      # @return [Gitlab::Fp::Result]
      def self.validate: (untyped context) -> untyped

      # @param [Hash] hash
      # @return [Hash]
      def self.make_hash_validatable_by_json_schemer: (untyped hash) -> untyped

      # @param [Hash] hash_to_validate
      # @return [Array]
      def self.validate_against_schema: (untyped hash_to_validate) -> untyped
    end
  end
end
