module WebIde
  module Settings
    class ExtensionMarketplaceGenerator
      # @param [Hash] context
      # @return [Hash]
      def self.generate: (untyped context) -> untyped

      # @param [User, nil] user
      # @return [Hash]
      def self.extension_marketplace_from_application_settings: () -> untyped
    end
  end
end
