module Gitlab
  module BitbucketImport
    module Stage
      class FinishImportWorker
        include StageMethods

        private

        def import: (untyped project) -> untyped
      end
    end
  end
end
