module Gitlab
  module BitbucketImport
    module Stage
      class ImportUsersWorker
        include StageMethods

        private

        def import: (untyped project) -> untyped

        def importer_class: () -> untyped
      end
    end
  end
end
