module WikiPages
  class EventCreateService
    @author: untyped

    # @param [User] author The event author
    def initialize: (untyped author) -> void

    def execute: (untyped slug, untyped page, untyped action, untyped event_fingerprint) -> untyped

    private

    attr_reader author: untyped
  end
end
