module Members
  class ExpirationDateUpdatedMailerPreview < ActionMailer::Preview
    def email: () -> untyped

    private

    def member: () -> untyped

    def member_source_type: () -> untyped
  end
end
