module Gitlab
  module Usage
    module Metrics
      module Instrumentations
        class ActiveProjectsInheritingIntegrationsMetric < BaseIntegrationsMetric
        end
      end
    end
  end
end
