module Gitlab
  module Usage
    module Metrics
      module Instrumentations
        class CountIssuesCreatedManuallyFromAlertsMetric < DatabaseMetric
          def value: () -> untyped
        end
      end
    end
  end
end
