module Gitlab
  module Usage
    module Metrics
      module Instrumentations
        class CountProjectsWithJiraDvcsIntegrationMetric < DatabaseMetric
          def initialize: (untyped metric_definition) -> void
        end
      end
    end
  end
end
