module Gitlab
  module Usage
    module Metrics
      module Instrumentations
        class CountDeploymentsMetric < DatabaseMetric
          @metric_relation: untyped

          def initialize: (untyped metric_definition) -> void

          private

          def type: () -> untyped

          def relation: () -> untyped
        end
      end
    end
  end
end
