module Gitlab
  module Usage
    module Metrics
      module Instrumentations
        class DistinctCountProjectsWithPackagesCleanupPolicyMetric < DatabaseMetric
        end
      end
    end
  end
end
