module Gitlab
  module Usage
    module Metrics
      module Instrumentations
        class JiraActiveIntegrationsMetric < DatabaseMetric
          def initialize: (untyped metric_definition) -> void

          private

          def allowed_types: () -> untyped
        end
      end
    end
  end
end
