module Gitlab
  module Usage
    module Metrics
      module Instrumentations
        class ProjectRunnerTokenExpirationEnabledMetric < GenericMetric
          def value: () -> (true | untyped)
        end
      end
    end
  end
end
