module Gitlab
  module Usage
    module Metrics
      module Instrumentations
        class SnowplowEnabledMetric < GenericMetric
          def value: () -> untyped
        end
      end
    end
  end
end
