module Database
  class ConsistencyCheckService
    @source_model: untyped

    @target_model: untyped

    @source_columns: untyped

    @target_columns: untyped

    @source_sort_column: untyped

    @target_sort_column: untyped

    @consistency_checker: untyped

    @min_id: untyped

    @max_id: untyped

    CURSOR_REDIS_KEY_TTL: untyped

    EMPTY_RESULT: { matches: 0, mismatches: 0, batches: 0, mismatches_details: ::Array[untyped] }

    def initialize: (source_model: untyped, target_model: untyped, source_columns: untyped, target_columns: untyped) -> void

    # This class takes two ActiveRecord models, and compares the selected columns
    # of the two models tables, for the purposes of checking the consistency of
    # mirroring of tables. For example Namespace and Ci::NamepaceMirror
    #
    # It compares up to 25 batches (1000 records / batch), or up to 30 seconds
    # for all the batches in total.
    #
    # It saves the cursor of the next start_id (cursor) in Redis. If the start_id
    # wasn't saved in Redis, for example, in the first run, it will choose some random start_id
    #
    # Example:
    #    service = Database::ConsistencyCheckService.new(
    #      source_model: Namespace,
    #      target_model: Ci::NamespaceMirror,
    #      source_columns: %w[id traversal_ids],
    #      target_columns: %w[namespace_id traversal_ids],
    #    )
    #    result = service.execute
    #
    # result is a hash that has the following fields:
    # - batches: Number of batches checked
    # - matches: The number of matched records
    # - mismatches: The number of mismatched records
    # - mismatches_details: It's an array that contains details about the mismatched records.
    #     each record in this array is a hash of format {id: ID, source_table: [...], target_table: [...]}
    #     Each record represents the attributes of the records in the two tables.
    # - start_id: The start id cursor of the current batch. <nil> means no records.
    # - next_start_id: The ID that can be used for the next batch iteration check. <nil> means no records
    def execute: () -> untyped

    private

    attr_reader source_model: untyped

    attr_reader target_model: untyped

    attr_reader source_columns: untyped

    attr_reader target_columns: untyped

    attr_reader source_sort_column: untyped

    attr_reader target_sort_column: untyped

    def consistency_checker: () -> untyped

    def next_start_id: () -> (nil | untyped)

    def min_id: () -> untyped

    def max_id: () -> untyped

    def fetch_next_start_id: () -> untyped

    # This returns some random start_id, so that we don't always start checking
    # from the start of the table, in case we lose the cursor in Redis.
    def random_start_id: () -> untyped

    def save_next_start_id: (untyped start_id) -> untyped

    def cursor_redis_shared_state_key: () -> ::String
  end
end
