module AlertManagement
  module HttpIntegrations
    class CreateService < BaseService
      def execute: () -> untyped

      private

      def error_no_permissions: () -> untyped
    end
  end
end
