class Profiles::EmailsController < Profiles::ApplicationController
  @primary_email: untyped

  @emails: untyped

  @show_unconfirmed_emails_alert: untyped

  @email: untyped

  include SafeFormatHelper

  def index: () -> untyped

  def show_unconfirmed_emails_alert: () -> untyped

  def create: () -> untyped

  def destroy: () -> untyped

  def resend_confirmation_instructions: () -> untyped

  private

  def email_params: () -> untyped

  def find_email: () -> untyped
end
