module Projects
  class ReadmeRendererService < BaseService
    TEMPLATE_PATH: untyped

    def execute: () -> untyped

    private

    def render: (untyped template_name) -> untyped

    def sanitized_filename: (untyped template_name) -> untyped
  end
end
