module Projects
  class RepositoryLanguagesService < BaseService
    def execute: () -> untyped

    private

    def perform_language_detection: () -> untyped

    def persisted_repository_languages: () -> untyped
  end
end
