module TwoFactor
  class DestroyOtpService < ::TwoFactor::BaseService
    def execute: () -> untyped

    private

    def authorized?: () -> untyped

    def disable_two_factor_otp: () -> untyped

    def notify_on_success: (untyped user) -> untyped
  end
end
