module API
  class GroupContainerRepositories < ::API::Base
    include PaginationParams

    include ::API::Helpers::ContainerRegistryHelpers

    REPOSITORY_ENDPOINT_REQUIREMENTS: untyped
  end
end
