# NuGet Package Manager Client API
#
# These API endpoints are not meant to be consumed directly by users. They are
# called by the NuGet package manager client when users run commands
# like `nuget install` or `nuget push`.
#
# This is the project level API.
module API
  class NugetProjectPackages < ::API::Base
    include ::API::Helpers::Authentication

    PACKAGE_FILENAME: "package.nupkg"

    SYMBOL_PACKAGE_FILENAME: "package.snupkg"

    API_KEY_HEADER: "X-Nuget-Apikey"

    def self.boundary_type: () -> :project
  end
end
