# #
# API endpoints for the RubyGem package registry
module API
  class RubygemPackages < ::API::Base
    include ::API::Helpers::Authentication

    # The Marshal version can be found by "#{Marshal::MAJOR_VERSION}.#{Marshal::MINOR_VERSION}"
    # Updating the version should require a GitLab API version change.
    MARSHAL_VERSION: "4.8"

    PACKAGE_FILENAME: "package.gem"

    FILE_NAME_REQUIREMENTS: { file_name: untyped }

    GEMSPEC_FILE_NAME_REQUIREMENTS: { file_name: untyped }
  end
end
