module API
  class WebCommits < ::API::Base
    GITALY_PUBLIC_KEY_CACHE_KEY: "gitaly_public_key"

    GITALY_UNAVAILABLE: "The git server, Gitaly, is not available at this time. Please contact your administrator."

    PUBLIC_KEY_NOT_FOUND: "Public key not found."
  end
end
