module Sidebars
  module Explore
    module Menus
      class ProjectsMenu < ::Sidebars::Menu
        def link: () -> untyped

        def title: () -> untyped

        def sprite_icon: () -> "project"

        def render?: () -> true

        def active_routes: () -> { page: ::Array[untyped] }
      end
    end
  end
end
