module Sidebars
  module Explore
    module Menus
      class SnippetsMenu < ::Sidebars::Menu
        def link: () -> untyped

        def title: () -> untyped

        def sprite_icon: () -> "snippet"

        def render?: () -> true

        def active_routes: () -> { controller: ::Array["explore/snippets"] }
      end
    end
  end
end
