# Imports a selected relation into an existing project, skipping any identified
# duplicates. Duplicates are matched on the `iid` of the record being imported.
module Projects
  module ImportExport
    class RelationImportService
      @current_user: untyped

      @params: untyped

      @project: untyped

      include ::Services::ReturnServiceResponses

      IMPORTABLE_RELATIONS: ::Array["issues" | "merge_requests" | "milestones" | "ci_pipelines"]

      # Creates a new RelationImportService.
      #
      # @param [User] current_user
      # @param [Hash] params
      # @option params [String] path The full path of the project
      # @option params [String] relation The relation to import. See IMPORTABLE_RELATIONS for permitted values.
      # @option params [UploadedFile] file The export archive containing the data to import
      def initialize: (current_user: untyped, params: untyped) -> void

      # Checks the validity of the chosen project and triggers the re-import of
      # the chosen relation.
      #
      # @return [Services::ServiceResponse]
      def execute: () -> untyped

      private

      attr_reader current_user: untyped

      attr_reader params: untyped

      def user_permitted?: () -> untyped

      def relation_valid?: () -> untyped

      def attach_import_file: () -> untyped

      def create_status_tracker: () -> untyped

      def project: () -> untyped

      def import_in_progress?: () -> untyped
    end
  end
end
