module Snippets
  class UpdateStatisticsService
    @snippet: untyped

    @statistics: untyped

    REPOSITORY_NOT_FOUND: :repository_not_found

    attr_reader snippet: untyped

    def initialize: (untyped snippet) -> void

    def execute: () -> untyped

    private

    def statistics: () -> untyped
  end
end
