module Files
  class UpdateService < Files::BaseService
    def create_commit!: () -> untyped

    def create_transformed_commit: (untyped content_or_lfs_pointer) -> untyped

    private

    def validate!: () -> untyped
  end
end
