module Gitlab
  module Config
    module Entry
      #
      # This mixin is responsible for adding DSL, which purpose is to
      # simplify the process of adding child nodes.
      #
      # This can be used only if parent node is a configuration entry that
      # holds a hash as a configuration value, for example:
      #
      # job:
      #   script: ...
      #   artifacts: ...
      #
      module Configurable
        extend ActiveSupport::Concern

        def compose!: (?untyped? deps) ?{ () -> untyped } -> (nil | untyped)

        # rubocop: disable CodeReuse/ActiveRecord
        def entry_create!: (untyped key, untyped value) -> untyped

        def skip_config_hash_validation?: () -> false
      end
    end
  end
end
