module Repositories
  class WebBasedCommitSigningSetting
    @repository: untyped

    def initialize: (untyped repository) -> void

    attr_reader repository: untyped

    def sign_commits?: () -> true
  end
end
