module Discussions
  class UpdateDiffPositionService < BaseService
    @tracer: untyped

    def execute: (untyped discussion) -> (nil | untyped)

    private

    def tracer: () -> untyped
  end
end
