module Routing
  module PipelineSchedulesHelper
    def pipeline_schedules_path: (untyped project, *untyped args) -> untyped

    def pipeline_schedule_path: (untyped schedule, *untyped args) -> untyped

    def edit_pipeline_schedule_path: (untyped schedule) -> untyped

    def play_pipeline_schedule_path: (untyped schedule, *untyped args) -> untyped
  end
end
