module Users
  class UnsubscribesController < ApplicationController
    @user: untyped

    @email: untyped

    def show: () -> untyped

    def create: () -> untyped

    # rubocop: disable CodeReuse/ActiveRecord
    def get_user: () -> untyped
  end
end
