module Sidebars
  module Groups
    module Menus
      class CiCdMenu < ::Sidebars::Menu
        def configure_menu_items: () -> true

        def title: () -> untyped

        def sprite_icon: () -> "rocket"

        def serialize_as_menu_item_args: () -> nil

        private

        def runners_menu_item: () -> untyped

        def show_runners?: () -> untyped
      end
    end
  end
end
