module Sidebars
  module Groups
    module Menus
      class ScopeMenu < ::Sidebars::Menu
        def link: () -> untyped

        def title: () -> untyped

        def active_routes: () -> { path: ::Array["groups#show" | "groups#details" | "groups#new" | "projects#new"] }

        def render?: () -> true

        def serialize_as_menu_item_args: () -> untyped
      end
    end
  end
end
