module Banzai
  module ReferenceParser
    class DesignParser < BaseParser
      def references_relation: () -> untyped

      def nodes_visible_to_user: (untyped user, untyped nodes) -> untyped

      def issues_for_nodes: (untyped nodes) -> untyped
    end
  end
end
