module Banzai
  module ReferenceParser
    class MilestoneParser < BaseParser
      def references_relation: () -> untyped

      private

      def can_read_reference?: (untyped user, untyped ref_project, untyped node) -> untyped
    end
  end
end
