module Projects
  module Security
    module ConfigurationHelper
      def security_upgrade_path: () -> untyped

      def vulnerability_training_docs_path: () -> untyped

      # Overridden in EE
      def group_configuration_path: () -> nil
    end
  end
end
