module Gitlab
  module Diff
    class PositionTracer
      class ImageStrategy < FileStrategy
        private

        def new_position: (untyped position, untyped diff_file) -> untyped
      end
    end
  end
end
