module Resolvers
  module Crm
    class OrganizationStateCountsResolver < BaseResolver
      include Gitlab::Graphql::Authorize::AuthorizeResource

      def resolve: (**untyped args) -> untyped
    end
  end
end
