class MergeRequestCleanupRefsWorker
  include ApplicationWorker

  include CronjobChildWorker

  include LimitedCapacity::Worker

  include Gitlab::Utils::StrongMemoize

  # Hard-coded to 4 for now. Will be configurable later on via application settings.
  # This means, there can only be 4 jobs running at the same time at maximum.
  MAX_RUNNING_JOBS: 4

  FAILURE_THRESHOLD: 3

  def perform_work: () -> (nil | untyped)

  def remaining_work_count: () -> untyped

  def max_running_jobs: () -> untyped

  private

  def merge_request: () -> untyped

  def merge_request_cleanup_schedule: () -> untyped
end
