class RemoveUnreferencedLfsObjectsWorker
  include ApplicationWorker

  # rubocop:disable Scalability/CronWorkerContext
  # This worker does not perform work scoped to a context
  include CronjobQueue

  def perform: () -> untyped
end
