module Authz
  class AdminConstraint
    def matches?: (untyped request) -> untyped

    private

    def user_is_admin?: (untyped request) -> untyped

    def admin_mode_enabled?: (untyped request) -> untyped
  end
end
