module Gitlab
  module Database
    module AsyncIndexes
      module MigrationHelpers
        include ::Gitlab::Database::PartitionHelpers

        def unprepare_async_index: (untyped table_name, untyped column_name, **untyped options) -> (nil | untyped)

        def unprepare_async_index_by_name: (untyped table_name, untyped index_name, **untyped options) -> (nil | untyped)

        def prepare_async_index: (untyped table_name, untyped column_name, **untyped options) -> (nil | untyped)

        def prepare_async_index_from_sql: (untyped definition) -> (nil | untyped)

        # Prepares an index for asynchronous destruction.
        #
        # Stores the index information in the postgres_async_indexes table to be removed later. The
        # index will be always be removed CONCURRENTLY, so that option does not need to be given.
        # Except for partitioned tables where indexes cannot be dropped using this option.
        # https://www.postgresql.org/docs/current/sql-dropindex.html
        #
        # If the requested index has already been removed, it is not stored in the table for
        # asynchronous destruction.
        def prepare_async_index_removal: (untyped table_name, untyped column_name, ?::Hash[untyped, untyped] options) -> (nil | untyped)

        def async_index_creation_available?: () -> untyped

        private

        def extract_table_and_index_names_from_concurrent_index!: (untyped definition) -> ::Array[untyped]

        # This raises `PgQuery::ParseError` if the given statement
        # is syntactically incorrect, therefore, validates that the
        # index definition is correct.
        def index_statement_from!: (untyped definition) -> untyped
      end
    end
  end
end
