module BatchLoaders
  class AwardEmojiVotesBatchLoader
    def self.load_award_emoji: (untyped object, ?awardable_class: untyped?) -> (::Array[untyped] | untyped)

    def self.load_upvotes: (untyped object, ?awardable_class: untyped?) -> untyped

    def self.load_downvotes: (untyped object, ?awardable_class: untyped?) -> untyped

    def self.load_votes_for: (untyped object, untyped vote_type, ?awardable_class: untyped?) -> untyped
  end
end
