module Types
  module Namespaces
    module LinkPaths
      class ProjectNamespaceLinksType < BaseObject
        @project: untyped

        @group: untyped

        def issues_list: () -> untyped

        def labels_manage: () -> untyped

        def new_project: () -> untyped

        def new_comment_template: () -> untyped

        def contribution_guide_path: () -> (nil | untyped)

        def new_work_item_email_address: () -> untyped

        def releases_path: () -> untyped

        def project_import_jira_path: () -> untyped

        def rss_path: () -> untyped

        def calendar_path: () -> untyped

        def namespace_full_path: () -> untyped

        def export_csv_path: () -> untyped

        def new_issue_path: () -> untyped

        def group_path: () -> untyped

        def issues_list_path: () -> untyped

        private

        def project: () -> untyped

        def group: () -> untyped
      end
    end
  end
end
