module RapidDiffs
  module Viewers
    class ViewerComponent < ViewComponent::Base
      @diff_file: untyped

      def self.viewer_name: () -> untyped

      def initialize: (diff_file: untyped) -> void

      def virtual_rendering_params: () -> nil
    end
  end
end
