module Achievements
  class AwardedAchievementsController < ApplicationController
    include Gitlab::Utils::StrongMemoize

    def accept: () -> (untyped | nil)

    private

    def user_achievement: () -> untyped

    def recipient_user?: () -> untyped

    def accept_and_redirect: () -> untyped

    def redirect_after_action: () -> untyped

    def render_invalid_link: () -> untyped
  end
end
