module ResolvesSnippets
  extend ActiveSupport::Concern

  include ResolvesIds

  def resolve: (**untyped args) -> untyped

  private

  def resolve_snippets: (untyped args) -> untyped

  def snippet_finder_params: (untyped args) -> untyped

  def options_by_type: (untyped type) -> untyped
end
