module Sidebars
  module Organizations
    class Panel < ::Sidebars::Panel
      include ::Sidebars::Concerns::SuperSidebarPanel

      def aria_label: () -> untyped

      def configure_menus: () -> untyped
    end
  end
end
