module Sidebars
  module Projects
    module Menus
      class ConfluenceMenu < ::Sidebars::Menu
        def link: () -> untyped

        def extra_container_html_options: () -> { class: "shortcuts-confluence" }

        def title: () -> untyped

        def image_path: () -> "confluence.svg"

        def render?: () -> untyped

        def active_routes: () -> { controller: :confluences }

        def serialize_as_menu_item_args: () -> untyped
      end
    end
  end
end
