module Sidebars
  module Projects
    module Menus
      class InfrastructureMenu < ::Sidebars::Menu
        def configure_menu_items: () -> (false | true)

        def extra_container_html_options: () -> { class: "shortcuts-infrastructure" }

        def title: () -> untyped

        def sprite_icon: () -> "cloud-gear"

        def serialize_as_menu_item_args: () -> nil

        private

        def feature_enabled?: () -> untyped

        def kubernetes_menu_item: () -> untyped

        def terraform_states_menu_item: () -> untyped

        def aws_menu_item: () -> untyped

        def google_cloud_menu_item: () -> untyped

        def google_oauth2_configured?: () -> untyped
      end
    end
  end
end
