module Atlassian
  module JiraConnect
    def self.app_name: () -> ::String

    def self.app_key: () -> untyped

    def self.display_name: () -> ("GitLab" | ::String)

    private

    def self.gitlab_host: () -> untyped

    def self.host_from_settings: () -> untyped
  end
end
