module Types
  module WorkItems
    module Widgets
      # rubocop:disable Graphql/AuthorizeTypes
      class LinkedItemsType < BaseObject
        def self.authorization_scopes: () -> untyped
      end
    end
  end
end
