module Gitlab
  module Ci
    module Status
      module Stage
        module Common
          def has_details?: () -> untyped

          def details_path: () -> untyped

          def has_action?: () -> false
        end
      end
    end
  end
end
