module Resolvers
  module Clusters
    module Agents
      module Authorizations
        class CiAccessResolver < BaseResolver
          alias project object

          def resolve: (*untyped) -> untyped
        end
      end
    end
  end
end
