module Gitlab
  module Ci
    module Pipeline
      module Seed
        class Context
          @pipeline: untyped

          @root_variables: untyped

          @logger: untyped

          @execution_configs: untyped

          @suspend_options: untyped

          attr_reader pipeline: untyped

          attr_reader root_variables: untyped

          attr_reader logger: untyped

          attr_reader execution_configs: untyped

          attr_reader suspend_options: untyped

          def initialize: (untyped pipeline, ?root_variables: untyped, ?logger: untyped?, ?suspend_options: untyped?) -> void

          def find_or_build_execution_config: (untyped attributes) -> untyped

          private

          def build_logger: () -> untyped
        end
      end
    end
  end
end
