module Types
  module Clusters
    class AgentType < BaseObject
      def self.authorization_scopes: () -> untyped

      def project: () -> untyped

      def web_path: () -> untyped
    end
  end
end
