module Releases
  class DestroyService < Releases::BaseService
    def execute: () -> untyped

    private

    def update_catalog_resource!: () -> (nil | untyped)

    def allowed?: () -> untyped
  end
end
