module PersonalAccessTokens
  class RevokeTokenFamilyService
    @token: untyped

    def initialize: (untyped token) -> void

    def execute: () -> untyped

    private

    attr_reader token: untyped

    def pat_family: () -> untyped
  end
end
