class Compare
  @compare: untyped

  @project: untyped

  @base_sha: untyped

  @straight: untyped

  @commits: untyped

  include Gitlab::Utils::StrongMemoize

  include ActsAsPaginatedDiff

  include ::Repositories::StreamableDiff

  attr_reader project: untyped

  def self.decorate: (untyped compare, untyped project) -> untyped

  def initialize: (untyped compare, untyped project, ?base_sha: untyped?, ?straight: bool) -> void

  # Return a Hash of parameters for passing to a URL helper
  #
  # See `namespace_project_compare_url`
  def to_param: () -> untyped

  def cache_key: () -> ::Array[untyped | :compare]

  def commits: (?limit: untyped?) -> untyped

  def start_commit: () -> untyped

  def head_commit: () -> untyped

  alias commit head_commit

  def start_commit_sha: () -> untyped

  def base_commit_sha: () -> untyped

  def head_commit_sha: () -> untyped

  def raw_diffs: (*untyped, **untyped) ?{ (?) -> untyped } -> untyped

  def diffs: (?untyped? diff_options) -> untyped

  def repository: () -> untyped

  def diff_refs: () -> untyped

  def diff_stats: () -> (nil | untyped)

  def changed_paths: () -> untyped

  def modified_paths: () -> untyped

  def first_diffs_slice: (untyped limit, ?::Hash[untyped, untyped] diff_options) -> untyped
end
