# Placeholder class for model that is implemented in EE
# It reserves '&' as a reference prefix, but the table does not exist in FOSS
class Epic < ApplicationRecord
  def self.link_reference_pattern: () -> nil

  def self.reference_prefix: () -> "&"

  def self.reference_prefix_escaped: () -> "&amp;"

  def self.alternative_reference_prefix: () -> "[epic:"

  def self.reference_postfix: () -> "]"
end
