class Identity < ApplicationRecord
  include Sortable

  include CaseSensitivity

  def ldap?: () -> untyped

  def self.normalize_uid: (untyped provider, untyped uid) -> untyped

  private

  def ensure_normalized_extern_uid: () -> (nil | untyped)

  def user_synced_attributes_metadata_from_provider?: () -> untyped

  def clear_user_synced_attributes: () -> untyped
end
