class NotificationSetting < ApplicationRecord
  include EachBatch

  include FromUnion

  # NOTE: Applicable unfound_translations.rb also needs to be updated when below events are changed.
  EMAIL_EVENTS: ::Array[:new_release | :new_note | :new_issue | :reopen_issue | :close_issue | :reassign_issue | :issue_due | :new_merge_request | :push_to_merge_request | :reopen_merge_request | :close_merge_request | :reassign_merge_request | :change_reviewer_merge_request | :merge_merge_request | :failed_pipeline | :fixed_pipeline | :success_pipeline | :moved_project | :merge_when_pipeline_succeeds]

  EXCLUDED_WATCHER_EVENTS: ::Array[:push_to_merge_request | :issue_due | :work_item_due | :success_pipeline | :approver]

  def self.email_events: (?untyped? source) -> untyped

  def self.allowed_fields: (?untyped? source) -> untyped

  def email_events: () -> untyped

  def self.find_or_create_for: (untyped source) -> untyped

  def self.reset_email_for_user!: (untyped email) -> untyped

  # Allow people to receive both failed pipeline/fixed pipeline notifications
  # if they already have custom notifications enabled,
  # as these are more like mentions than the other custom settings.
  def failed_pipeline: () -> untyped

  alias failed_pipeline? failed_pipeline

  def fixed_pipeline: () -> untyped

  alias fixed_pipeline? fixed_pipeline

  def event_enabled?: (untyped event) -> untyped

  def notification_email_verified: () -> (nil | untyped)
end
