class Todo < ApplicationRecord
  include Sortable

  include FromUnion

  include EachBatch

  # Time to wait for todos being removed when not visible for user anymore.
  # Prevents TODOs being removed by mistake, for example, removing access from a user
  # and giving it back again.
  WAIT_FOR_DELETE: untyped

  # Actions
  ASSIGNED: 1

  MENTIONED: 2

  BUILD_FAILED: 3

  MARKED: 4

  APPROVAL_REQUIRED: 5

  UNMERGEABLE: 6

  DIRECTLY_ADDRESSED: 7

  MERGE_TRAIN_REMOVED: 8

  REVIEW_REQUESTED: 9

  MEMBER_ACCESS_REQUESTED: 10

  REVIEW_SUBMITTED: 11

  OKR_CHECKIN_REQUESTED: 12

  ADDED_APPROVER: 13

  SSH_KEY_EXPIRED: 14

  SSH_KEY_EXPIRING_SOON: 15

  DUO_PRO_ACCESS_GRANTED: 16

  DUO_ENTERPRISE_ACCESS_GRANTED: 17

  DUO_CORE_ACCESS_GRANTED: 18

  DUO_WORKFLOW_INPUT_REQUIRED: 19

  # EE Action names should be defined in EE_ACTION_NAMES in ee/app/models/ee/todo.rb
  ACTION_NAMES: ::Hash[untyped, :assigned | :review_requested | :mentioned | :build_failed | :marked | :approval_required | :unmergeable | :directly_addressed | :member_access_requested | :review_submitted | :ssh_key_expired | :ssh_key_expiring_soon]

  ACTIONS_MULTIPLE_ALLOWED: ::Array[untyped]

  # EE parentless action types should be defined in EE_PARENTLESS_ACTION_TYPES in ee/app/models/ee/todo.rb
  PARENTLESS_ACTION_TYPES: ::Array[untyped]

  BATCH_DELETE_SIZE: 100

  # Returns all todos for the given group ids and their descendants.
  #
  # group_ids - Group Ids to retrieve todos for.
  #
  # Returns an `ActiveRecord::Relation`.
  def self.for_group_ids_and_descendants: (untyped group_ids) -> untyped

  def self.pending_for_expiring_ssh_keys: (untyped ssh_key_ids) -> untyped

  # Returns `true` if the current user has any todos for the given target with the optional given state.
  #
  # target - The value of the `target_type` column, such as `Issue`.
  # state - The value of the `state` column, such as `pending` or `done`.
  def self.any_for_target?: (untyped target, ?untyped? state) -> untyped

  # Updates attributes of a relation of todos to the new state.
  #
  # new_attributes - The new attributes of the todos.
  #
  # Returns an `Array` containing the IDs of the updated todos.
  def self.batch_update: (**untyped new_attributes) -> untyped

  # Priority sorting isn't displayed in the dropdown, because we don't show
  # milestones, but still show something if the user has a URL with that
  # selected.
  def self.sort_by_attribute: (untyped method) -> untyped

  def self.sort_by_snoozed_and_creation_dates: (?direction: ::Symbol) -> untyped

  # Order by priority depending on which issue/merge request the Todo belongs to
  # Todos with highest priority first then oldest todos
  # Need to order by created_at last because of differences on Mysql and Postgres when joining by type "Merge_request/Issue"
  def self.order_by_labels_priority: (?asc: bool) -> untyped

  def self.action_names: () -> untyped

  def self.parentless_action_types: () -> untyped

  def self.distinct_user_ids: () -> untyped

  # Count pending todos grouped by user_id and state
  # so we can utilize the index on state / user id.
  def self.pending_count_by_user_id: () -> untyped

  def resource_parent: () -> untyped

  def build_failed?: () -> untyped

  def assigned?: () -> untyped

  def review_requested?: () -> untyped

  def member_access_requested?: () -> untyped

  def member_access_type: () -> untyped

  def access_request_url: (?only_path: bool) -> (untyped | untyped | "")

  def done?: () -> untyped

  def action_name: () -> untyped

  def body: () -> untyped

  def for_commit?: () -> untyped

  def for_design?: () -> untyped

  def for_issue_or_work_item?: () -> untyped

  def parentless_type?: () -> untyped

  # override to return commits, which are not active record
  def target: () -> untyped

  def target_reference: () -> untyped

  def target_url: () -> (nil | untyped)

  private

  def set_sharding_key: () -> untyped

  def build_work_item_target_url: () -> untyped

  def build_merge_request_target_url: () -> untyped

  def build_design_target_url: () -> untyped

  def build_alert_target_url: () -> untyped

  def build_commit_target_url: () -> untyped

  def build_project_target_url: () -> (nil | untyped)

  def build_group_target_url: () -> (nil | untyped)

  def build_ssh_key_target_url: () -> untyped

  def build_wiki_page_target_url: () -> untyped
end
