class ZoomMeeting < ApplicationRecord
  include Importable

  include UsageStatistics

  def self.canonical_meeting: (untyped issue) -> untyped

  def self.canonical_meeting_url: (untyped issue) -> untyped
end
