module IncidentManagementFeatureFlag
  extend ActiveSupport::Concern

  private

  def check_incidents_feature_flag: () -> (nil | untyped)

  def handle_feature_flag_enabled_response: () -> untyped
end
