module IssuableLinks
  def index: () -> untyped

  def create: () -> untyped

  def destroy: () -> untyped

  private

  def issuables: () -> untyped

  def list_service: () -> untyped

  def create_params: () -> untyped

  def create_service: () -> untyped

  def destroy_service: () -> untyped
end
