module SnippetAuthorizations
  extend ActiveSupport::Concern

  private

  def authorize_read_snippet!: () -> (untyped | nil)

  def authorize_update_snippet!: () -> (untyped | nil)

  def authorize_admin_snippet!: () -> (untyped | nil)

  def authorize_create_snippet!: () -> (untyped | nil)
end
