module SynchronizeBroadcastMessageDismissals
  extend ActiveSupport::Concern

  def synchronize_broadcast_message_dismissals: (untyped user) -> untyped

  private

  def create_dismissal_cookie: (untyped dismissal) -> untyped
end
