module Gitlab
  module Database
    module BackgroundOperation
      module Observability
        module Events
          # Event responsible for logging any worker state transition event
          # E.g: from => pending, to => running
          class WorkerTransitionEvent < Event
            LOG_EVENT: "background_operation_worker_transition_event"

            def payload: () -> { message: untyped, previous_state: untyped, new_state: untyped, on_hold_until: untyped, priority: untyped, job_class_name: untyped, batch_class_name: untyped, table_name: untyped, column_name: untyped, gitlab_schema: untyped, job_arguments: untyped }
          end
        end
      end
    end
  end
end
