module Analytics
  module CycleAnalytics
    class MergeRequestStageEvent < ApplicationRecord
      include StageEventModel

      def self.project_column: () -> :target_project_id

      def self.issuable_id_column: () -> :merge_request_id

      def self.issuable_model: () -> untyped

      def self.assignees_model: () -> untyped
    end
  end
end
