module Members
  class AccessRequestedMailer < ApplicationMailer
    def email: () -> (nil | untyped)

    private

    def valid_to_email?: () -> (false | true)

    def target_type: () -> untyped

    def member: () -> untyped

    def recipient: () -> untyped

    def email_subject_text: () -> ::String
  end
end
