module Members
  class InviteAcceptedMailer < ApplicationMailer
    def email: () -> (nil | untyped)

    private

    def body_text: () -> untyped

    def target_model_name: () -> untyped

    def valid_to_email?: () -> (false | untyped)

    def member: () -> untyped
  end
end
