module Gitlab
  module FogbugzImport
    class Repository
      @raw_data: untyped

      attr_accessor raw_data: untyped

      def initialize: (untyped raw_data) -> void

      def valid?: () -> untyped

      def id: () -> untyped

      def name: () -> untyped

      def safe_name: () -> untyped

      def path: () -> untyped
    end
  end
end
