module Gitlab
  module CycleAnalytics
    module Summary
      module Defaults
        def identifier: () -> untyped

        # :nocov: the class including this concern is expected to test this method.
        def title: () -> untyped

        # :nocov: the class including this concern is expected to test this method.
        def value: () -> untyped

        def links: () -> ::Array[untyped]
      end
    end
  end
end
