module Gitlab
  module CycleAnalytics
    module Summary
      class Deploy < Base
        @value: untyped

        def identifier: () -> :deploys

        def title: () -> untyped

        def value: () -> untyped

        private

        def deployments_count: () -> untyped
      end
    end
  end
end
