module GpgKeys
  class CreateService < Keys::BaseService
    def execute: () -> untyped

    private

    def validate: (untyped key) -> (false | untyped)

    def create: (untyped key) -> untyped
  end
end
