module Gitlab
  module Ci
    module Parsers
      module Accessibility
        class Pa11y
          def parse!: (untyped json_data, untyped accessibility_report) -> untyped

          private

          def parse_all: (untyped root, untyped accessibility_report) -> (nil | untyped)
        end
      end
    end
  end
end
