module Pajamas
  class BreadcrumbComponent < Pajamas::Component
    @html_options: untyped

    def initialize: (**untyped html_options) -> void

    private

    attr_reader html_options: untyped
  end
end
