module Pajamas
  class EmptyStateComponent < Pajamas::Component
    @compact: untyped

    @title: untyped

    @svg_path: untyped

    @primary_button_text: untyped

    @primary_button_link: untyped

    @primary_button_options: untyped

    @secondary_button_text: untyped

    @secondary_button_link: untyped

    @secondary_button_options: untyped

    @empty_state_options: untyped

    # @param [Boolean] compact
    # @param [String] title
    # @param [String] svg_path
    # @param [String] primary_button_text
    # @param [String] primary_button_link
    # @param [Hash] primary_button_options
    # @param [String] secondary_button_text
    # @param [String] secondary_button_link
    # @param [Hash] secondary_button_options
    # @param [Hash] empty_state_options
    def initialize: (?compact: bool, ?title: untyped?, ?svg_path: untyped?, ?primary_button_text: untyped?, ?primary_button_link: untyped?, ?primary_button_options: ::Hash[untyped, untyped], ?secondary_button_text: untyped?, ?secondary_button_link: untyped?, ?secondary_button_options: ::Hash[untyped, untyped], ?empty_state_options: ::Hash[untyped, untyped]) -> void
  end
end
