module JiraImport
  class ServerUsersMapperService < UsersMapperService
    private

    def url: () -> ::String

    def jira_user_id: (untyped jira_user) -> untyped

    def jira_user_name: (untyped jira_user) -> untyped
  end
end
