module Gitlab
  module HookData
    class WikiPageBuilder < BaseBuilder
      alias wiki_page object

      def build: () -> untyped

      def page_content: () -> untyped

      def uploads_prefix: () -> untyped
    end
  end
end
