module Import
  module Github
    class GistsImportService < ::BaseService
      @current_user: untyped

      @params: untyped

      @client: untyped

      @import_status: untyped

      def initialize: (untyped user, untyped client, untyped params) -> void

      def execute: () -> untyped

      private

      def import_status: () -> untyped

      def encrypted_token: () -> untyped

      def start_import: () -> untyped

      def check_user_token: () -> untyped
    end
  end
end
