module Gitlab
  module GithubImport
    module PullRequests
      class ImportMergedByWorker
        include ObjectImporter

        def representation_class: () -> untyped

        def importer_class: () -> untyped

        def object_type: () -> :pull_request_merged_by
      end
    end
  end
end
