module ContainerRegistry
  module Protection
    class Rule < ApplicationRecord
      def self.for_action_exists?: (action: untyped, access_level: untyped, repository_path: untyped) -> (false | untyped)

      #
      # Accepts a list of projects and repository paths and returns a result set
      # indicating whether the repository path is protected.
      #
      # @param [Array<Array>] projects_repository_paths an array of arrays where each sub-array contains a project id
      # and a repository path.
      # @return [ActiveRecord::Result] a result set indicating whether each project and repository path is protected.
      #
      # Example:
      #   ContainerRegistry::Protection::Rule.for_push_exists_for_projects_and_repository_paths([
      #     [1, '/my_group/my_project_1/image_1'],
      #     [1, '/my_group/my_project_1/image_2'],
      #     [2, '/my_group/my_project_2/image_1'],
      #     ...
      #   ])
      #
      #   [
      #     {'project_id' => 1, 'repository_path_pattern' => '/my_group/my_project_1/image_1', 'protected' => true},
      #     {'project_id' => 1, 'repository_path_pattern' => '/my_group/my_project_1/image_2', 'protected' => false},
      #     {'project_id' => 2, 'repository_path_pattern' => '/my_group/my_project_2/image_1', 'protected' => true},
      #     ...
      #   ]
      #
      def self.for_push_exists_for_projects_and_repository_paths: (untyped projects_repository_paths) -> untyped

      private

      def path_pattern_starts_with_project_full_path: () -> (nil | untyped)

      def at_least_one_minimum_access_level_must_be_present: () -> (nil | untyped)
    end
  end
end
