module VsCode
  module Settings
    class VsCodeManifestPresenter < Gitlab::View::Presenter::Simple
      @settings: untyped

      attr_reader settings: untyped

      def initialize: (untyped settings) -> void

      def latest: () -> untyped

      def session: () -> untyped
    end
  end
end
