module Analytics
  module CycleAnalytics
    class StageFinder
      @parent: untyped

      @stage_id: untyped

      def initialize: (parent: untyped, stage_id: untyped) -> void

      def execute: () -> untyped

      private

      attr_reader parent: untyped

      attr_reader stage_id: untyped

      def build_in_memory_stage_by_name: () -> untyped

      def find_in_memory_stage: () -> untyped
    end
  end
end
