module IssueLinks
  class DestroyService < IssuableLinks::DestroyService
    include IncidentManagement::UsageData

    def success: (*untyped, **untyped) ?{ (?) -> untyped } -> untyped

    private

    def permission_to_remove_relation?: () -> untyped

    def track_event: () -> untyped
  end
end
