module Banzai
  module Pipeline
    class BasePipeline
      self.@html_pipeline: untyped

      def self.filters: () -> untyped

      def self.transform_context: (untyped context) -> untyped

      def self.html_pipeline: () -> untyped
    end
  end
end
