module Banzai
  module Pipeline
    class MarkupPipeline < BasePipeline
      self.@filters: untyped

      def self.filters: () -> untyped

      def self.transform_context: (untyped context) -> untyped
    end
  end
end
