module Banzai
  module Pipeline
    class PostProcessPipeline < BasePipeline
      self.@filters: untyped

      def self.filters: () -> untyped

      def self.internal_link_filters: () -> ::Array[untyped]

      def self.transform_context: (untyped context) -> untyped
    end
  end
end
