module Types
  module Notes
    class NoteType < BaseObject
      def self.authorization_scopes: () -> untyped

      def system_note_icon_name: () -> (untyped | nil)

      def project: () -> untyped

      # We now support also SyntheticNote notes as a NoteType, but SyntheticNote does not have a real note ID,
      # as SyntheticNote is generated dynamically from a ResourceEvent instance.
      def id: () -> untyped

      def position: () -> (untyped | nil)
    end
  end
end
