# CronTimezoneValidator
#
# Custom validator for CronTimezone.
class CronTimezoneValidator < ActiveModel::EachValidator
  def validate_each: (untyped record, untyped attribute, untyped value) -> untyped
end
