module Gitlab
  class ConanToken
    @access_token_id: untyped

    @user_id: untyped

    @expire_at: untyped

    HMAC_KEY: "gitlab-conan-packages"

    MAX_CONAN_TOKEN_EXPIRE_TIME: untyped

    attr_reader access_token_id: untyped

    attr_reader user_id: untyped

    attr_reader expire_at: untyped

    def self.from_personal_access_token: (untyped token_id, untyped personal_token) -> (nil | untyped)

    def self.from_job: (untyped job) -> (nil | untyped)

    def self.from_deploy_token: (untyped deploy_token) -> untyped

    def self.decode: (untyped jwt) -> untyped

    def self.secret: () -> untyped

    def initialize: (access_token_id: untyped, user_id: untyped, ?expire_at: untyped?) -> void

    def to_jwt: () -> untyped

    private

    def hmac_token: () -> untyped
  end
end
