module Gitlab
  class DeployKeyAccess < UserAccess
    @deploy_key: untyped

    @user: untyped

    @container: untyped

    def initialize: (untyped deploy_key, ?container: untyped?) -> void

    def can_push_for_ref?: (untyped ref) -> untyped

    private

    attr_reader deploy_key: untyped

    def can_collaborate?: (untyped _ref) -> untyped

    def project_has_active_user_keys?: () -> untyped
  end
end
