module Gitlab
  # Retrieving of parent or child objects based on a base ActiveRecord relation.
  #
  # This class uses recursive CTEs and as a result will only work on PostgreSQL.
  class ObjectHierarchy
    @ancestors_base: untyped

    @descendants_base: untyped

    @model: untyped

    @unscoped_model: untyped

    @options: untyped

    DEPTH_COLUMN: :depth

    attr_reader ancestors_base: untyped

    attr_reader descendants_base: untyped

    attr_reader model: untyped

    attr_reader options: untyped

    attr_reader unscoped_model: untyped

    # ancestors_base - An instance of ActiveRecord::Relation for which to
    #                  get parent objects.
    # descendants_base - An instance of ActiveRecord::Relation for which to
    #                    get child objects. If omitted, ancestors_base is used.
    def initialize: (untyped ancestors_base, ?untyped descendants_base, ?options: ::Hash[untyped, untyped]) -> void

    # Returns the set of descendants of a given relation, but excluding the given
    # relation
    def descendants: () -> untyped

    # Returns the maximum depth starting from the base
    # A base object with no children has a maximum depth of `1`
    def max_descendants_depth: () -> untyped

    # Returns the set of ancestors of a given relation, but excluding the given
    # relation
    #
    # Passing an `upto` will stop the recursion once the specified parent_id is
    # reached. So all ancestors *lower* than the specified ancestor will be
    # included.
    def ancestors: (?upto: untyped?, ?hierarchy_order: untyped?) -> untyped

    # Returns a relation that includes the ancestors_base set of objects
    # and all their ancestors (recursively).
    #
    # Passing an `upto` will stop the recursion once the specified parent_id is
    # reached. So all ancestors *lower* than the specified ancestor will be
    # included.
    #
    # Passing a `hierarchy_order` with either `:asc` or `:desc` will cause the
    # recursive query order from most nested object to root or from the root
    # ancestor to most nested object respectively. This uses a `depth` column
    # where `1` is defined as the depth for the base and increment as we go up
    # each parent.
    #
    # Note: By default the order is breadth-first
    # rubocop: disable CodeReuse/ActiveRecord
    def base_and_ancestors: (?upto: untyped?, ?hierarchy_order: untyped?) -> untyped

    # Returns a relation that includes the descendants_base set of objects
    # and all their descendants (recursively).
    #
    # When `with_depth` is `true`, a `depth` column is included where it starts with `1` for the base objects
    # and incremented as we go down the descendant tree
    def base_and_descendants: (?with_depth: bool) -> untyped

    # Returns a relation that includes ID of the descendants_base set of objects
    # and all their descendants IDs (recursively).
    def base_and_descendant_ids: () -> untyped

    # Returns a relation that includes the base objects, their ancestors,
    # and the descendants of the base objects.
    #
    # The resulting query will roughly look like the following:
    #
    #     WITH RECURSIVE ancestors AS ( ... ),
    #       descendants AS ( ... )
    #     SELECT *
    #     FROM (
    #       SELECT *
    #       FROM ancestors namespaces
    #
    #       UNION
    #
    #       SELECT *
    #       FROM descendants namespaces
    #     ) groups;
    #
    # Using this approach allows us to further add criteria to the relation with
    # Rails thinking it's selecting data the usual way.
    #
    # If nested objects are not supported, ancestors_base is returned.
    # rubocop: disable CodeReuse/ActiveRecord
    def all_objects: () -> untyped

    private

    # Remove the extra `depth` field using an INNER JOIN to avoid breaking UNION queries
    # and ordering the rows based on the `depth` column to maintain the row order.
    #
    # rubocop: disable CodeReuse/ActiveRecord
    def remove_depth_and_maintain_order: (untyped relation, ?hierarchy_order: ::Symbol) -> untyped

    # rubocop: disable CodeReuse/ActiveRecord
    def base_and_ancestors_cte: (?untyped? stop_id, ?untyped? hierarchy_order) -> untyped

    # rubocop: disable CodeReuse/ActiveRecord
    def base_and_descendants_cte: (?with_depth: bool) -> untyped

    # rubocop: disable CodeReuse/ActiveRecord
    def base_and_descendant_ids_cte: () -> untyped

    def objects_table: () -> untyped

    def parent_id_column: (untyped cte) -> untyped

    def objects_id_columns: () -> untyped

    def from_tables: (untyped cte) -> ::Array[untyped]

    def ancestor_conditions: (untyped cte) -> untyped

    def descendant_conditions: (untyped cte) -> untyped

    def read_only: (untyped relation) -> untyped
  end
end
