module Gitlab
  class ProjectStatsRefreshConflictsLogger
    def self.warn_artifact_deletion_during_stats_refresh: (project_id: untyped, method: untyped) -> untyped

    def self.warn_request_rejected_during_stats_refresh: (untyped project_id) -> untyped

    def self.warn_skipped_artifact_deletion_during_stats_refresh: (project_ids: untyped, method: untyped) -> untyped
  end
end
