module Gitlab
  class RouteMap
    @map: untyped

    FormatError: untyped

    def initialize: (untyped data) -> void

    def public_path_for_source_path: (untyped path) -> (nil | untyped)

    private

    def parse_entry: (untyped entry) -> { source: untyped, public: untyped }
  end
end
