module Gitlab
  class SampleDataTemplate < ProjectTemplate
    def self.localized_templates_table: () -> ::Array[untyped]

    def self.all: () -> untyped

    def self.archive_directory: () -> untyped
  end
end
