module Gitlab
  class UsageDataMetrics
    # Build the Usage Ping JSON payload from metrics YAML definitions which have instrumentation class set
    def self.uncached_data: () -> untyped

    private

    def self.build_payload: (untyped method_symbol) -> untyped
  end
end
