module Gitlab
  module WikiPages
    # To avoid this situation, we enforce these limits when editing pages
    # through the GitLab web interface and API:
    MAX_TITLE_BYTES: 245

    MAX_DIRECTORY_BYTES: 255

    # Limit the number of pages displayed in the wiki sidebar.
    MAX_SIDEBAR_PAGES: 15
  end
end
