module Gitlab
  class ZoomLinkExtractor
    @text: untyped

    ZOOM_REGEXP: ::Regexp

    def initialize: (untyped text) -> void

    def links: () -> untyped

    def match?: () -> untyped
  end
end
