# Include atomic internal id generation scheme for a model
#
# This allows us to atomically generate internal ids that are
# unique within a given scope.
#
# For example, let's generate internal ids for Issue per Project:
# ```
# class Issue < ApplicationRecord
#   has_internal_id :iid, scope: :project, init: ->(s) { s.project.issues.maximum(:iid) }
# end
# ```
#
# This generates unique internal ids per project for newly created issues.
# The generated internal id is saved in the `iid` attribute of `Issue`.
#
# This concern uses InternalId records to facilitate atomicity.
# In the absence of a record for the given scope, one will be created automatically.
# In this situation, the `init` block is called to calculate the initial value.
# In the example above, we calculate the maximum `iid` of all issues
# within the given project.
#
# Note that a model may have more than one internal id associated with possibly
# different scopes.
module AtomicInternalId
  extend ActiveSupport::Concern

  MissingValueError: untyped

  def self.scope_attrs: (untyped scope_value) -> (::Hash[untyped, untyped] | nil)

  def internal_id_scope_attrs: (untyped scope) -> untyped

  def internal_id_scope_usage: () -> untyped

  def self.scope_usage: (untyped klass) -> untyped

  def self.project_init: (untyped klass, ?::Symbol column_name) -> untyped

  def self.group_init: (untyped klass, ?::Symbol column_name) -> untyped

  def self.namespace_init: (untyped klass, ?::Symbol column_name) -> untyped

  def internal_id_read_scope: (untyped scope) -> untyped

  class Supply
    @generator: untyped

    attr_reader generator: untyped

    def initialize: (untyped generator) -> void

    def next_value: () -> untyped
  end
end
