# Support for both BCrypt and PBKDF2+SHA512 user passwords
# Meant to be used exclusively with User model but extracted
# to a concern for isolation and clarity.
module EncryptedUserPassword
  @password: untyped

  extend ActiveSupport::Concern

  BCRYPT_PREFIX: "$2a$"

  PBKDF2_SHA512_PREFIX: "$pbkdf2-sha512$"

  PBKDF2_SALT_LENGTH: 64

  BCRYPT_STRATEGY: :bcrypt

  PBKDF2_SHA512_STRATEGY: :pbkdf2_sha512

  # Use Devise DatabaseAuthenticatable#authenticatable_salt
  # unless encrypted password is PBKDF2+SHA512.
  def authenticatable_salt: () -> untyped

  # Called by Devise during database authentication.
  # Also migrates the user password to the configured
  # encryption type (BCrypt or PBKDF2+SHA512), if needed.
  def valid_password?: (untyped password) -> (false | untyped)

  def password=: (untyped new_password) -> (nil | untyped)

  def migrated_password?: () -> (false | true)

  private

  # Generates a hashed password for the configured encryption method
  # (BCrypt or PBKDF2+SHA512).
  # DOES NOT SAVE IT IN ANY WAY.
  def hash_this_password: (untyped password) -> untyped

  def password_strategy: () -> (untyped | :unknown)

  def pbkdf2_password?: () -> untyped

  def bcrypt_password?: () -> untyped

  def password_matches?: (untyped password) -> (untyped | untyped | nil)

  def migrate_password!: (untyped password) -> (true | untyped)

  def bcrypt_password_matches_current_stretches?: () -> (false | untyped)

  def pbkdf2_password_matches_salt_length?: () -> (false | untyped)

  def encryptor: () -> untyped
end
