# Add methods used by the projects API
module ProjectAPICompatibility
  extend ActiveSupport::Concern

  def build_git_strategy=: (untyped value) -> untyped

  def auto_devops_enabled=: (untyped value) -> untyped

  def auto_devops_deploy_strategy=: (untyped value) -> untyped
end
