# == Referable concern
#
# Contains functionality related to making a model referable in Markdown, such
# as "#1", "!2", "~3", etc.
module Referable
  extend ActiveSupport::Concern

  # Returns the String necessary to reference this object in Markdown
  #
  # from - Referring parent object
  #
  # This should be overridden by the including class.
  #
  # Examples:
  #
  #   Issue.first.to_reference               # => "#1"
  #   Issue.last.to_reference(other_project) # => "cross-project#1"
  #
  # Returns a String
  def to_reference: (?untyped? _from, full: untyped) -> ""

  # If this referable object can serve as the base for the
  # reference of child objects (e.g. projects are the base of
  # issues), but it is formatted differently, then you may wish
  # to override this method.
  def to_reference_base: (?untyped? from, full: untyped, ?absolute_path: bool) -> untyped

  def reference_link_text: (?untyped? from) -> untyped

  def referable_inspect: () -> ::String
end
