module Integrations
  class Packagist < Integration
    include HasWebHook

    def self.title: () -> "Packagist"

    def self.description: () -> untyped

    def self.to_param: () -> "packagist"

    def self.supported_events: () -> ::Array["push" | "merge_request" | "tag_push"]

    def execute: (untyped data) -> (nil | untyped)

    def test: (untyped data) -> ({ success: false, result: untyped } | { success: true, result: untyped })

    def hook_url: () -> ::String

    def url_variables: () -> { "username" => untyped, "token" => untyped }
  end
end
