module Integrations
  class Slack < Integration
    include Base::SlackNotification

    include SlackMattermostNotifier

    include SlackMattermostFields

    def self.title: () -> "Slack notifications"

    def self.description: () -> "Send notifications about project events to Slack."

    def self.to_param: () -> "slack"

    def self.webhook_help: () -> "https://hooks.slack.com/services/..."

    private

    def metrics_key_prefix: () -> "i_ecosystem_slack_service"
  end
end
