module Gitlab
  module SafeRequestStore
    NULL_STORE: untyped

    extend Forwardable

    def self.store: () -> untyped

    # Access to the backing storage of the request store. This returns an object
    # with `[]` and `[]=` methods that does not discard values.
    #
    # This can be useful if storage is needed for a delimited purpose, and the
    # forgetful nature of the null store is undesirable.
    def self.storage: () -> untyped

    # This method accept an options hash to be compatible with
    # ActiveSupport::Cache::Store#write method. The options are
    # not passed to the underlying cache implementation because
    # RequestStore#write accepts only a key, and value params.
    def self.write: (untyped key, untyped value, ?untyped? _options) -> untyped

    def self.delete_if: () { (untyped) -> untyped } -> (nil | untyped)

    def self.ensure_request_store: () { () -> untyped } -> untyped

    private

    def self.enabling_request_store: () { () -> untyped } -> untyped
  end
end
