module Members
  class PendingInvitationsFinder
    @invite_emails: untyped

    def initialize: (untyped invite_emails) -> void

    def execute: () -> untyped

    private

    attr_reader invite_emails: untyped
  end
end
