module API
  module Helpers
    module DiscussionsHelpers
      def self.feature_category_per_noteable_type: () -> ::Hash[untyped, :team_planning | :source_code_management | :code_review_workflow]
    end
  end
end
