module API
  module Helpers
    module MembersHelpers
      extend Grape::API::Helpers

      def find_source: (untyped source_type, untyped id) -> untyped

      def authorize_read_source_member!: (untyped source_type, untyped source) -> untyped

      def authorize_admin_source_member!: (untyped source_type, untyped source) -> untyped

      def authorize_invite_source_member!: (untyped source_type, untyped source) -> untyped

      def authorize_update_source_member!: (untyped source_type, untyped member) -> untyped

      def authorize_admin_source!: (untyped source_type, untyped source) -> untyped

      # rubocop: disable CodeReuse/ActiveRecord
      def retrieve_members: (untyped source, params: untyped, ?deep: bool) -> untyped

      def retrieve_member_invitations: (untyped source, ?untyped? query) -> untyped

      def source_members: (untyped source) -> untyped

      def find_all_members: (untyped source) -> untyped

      def find_all_members_for_project: (untyped project) -> untyped

      def find_all_members_for_group: (untyped group) -> untyped

      def present_members: (untyped members) -> untyped

      def present_member_invitations: (untyped invitations) -> untyped

      def present_members_with_invited_private_group_accessibility: (untyped members, untyped source) -> untyped

      def add_single_member: (untyped create_service_params) -> untyped

      def present_put_membership_response: (untyped result) -> untyped

      def check_existing_membership: (untyped create_service_params) -> untyped

      def add_multiple_members?: (untyped user_id, untyped username) -> untyped

      def self.member_access_levels: () -> untyped

      private

      def member_already_exists?: (untyped source, untyped user_id) -> untyped

      def present_add_single_member_response: (untyped result, untyped member) -> untyped
    end
  end
end
