module API
  module Helpers
    module PerformanceBarHelpers
      def set_peek_enabled_for_current_request: () -> untyped

      def perf_bar_cookie_enabled?: () -> untyped

      def perf_bar_allowed_for_user?: () -> untyped
    end
  end
end
