module API
  module Helpers
    class Version
      @version: untyped

      @root_url: untyped

      include Helpers::RelatedResourcesHelpers

      def initialize: (untyped version) -> void

      def root_path: () -> untyped

      def root_url: () -> untyped

      def to_s: () -> untyped
    end
  end
end
