module API
  module Helpers
    module WikisHelpers
      def self.wiki_resource_kinds: () -> ::Array[:projects]

      def find_container: (untyped kind) -> untyped

      def wiki_page: (?untyped? version) -> untyped

      def commit_params: (untyped attrs) -> untyped
    end
  end
end
