module DeviceRegistrationHelper
  def device_registration_data: (current_password_required: untyped, target_path: untyped, webauthn_error: untyped) -> { initial_error: untyped, target_path: untyped, two_factor_auth_path: untyped, password_required: untyped }
end
