module FeatureFlagsHelper
  include ::API::Helpers::RelatedResourcesHelpers

  def unleash_api_url: (untyped project) -> untyped

  def unleash_api_instance_id: (untyped project) -> untyped

  def edit_feature_flag_data: () -> { endpoint: untyped, project_id: untyped, feature_flags_path: untyped, environments_endpoint: untyped, strategy_type_docs_page_path: untyped, environments_scope_docs_path: untyped }
end
