module GraphHelper
  def refs: (untyped repo, untyped commit) -> untyped

  def parents_zip_spaces: (untyped parents, untyped parent_spaces) -> untyped

  def should_render_quality_summary: () -> false
end
