module HooksHelper
  def webhook_form_data: (untyped hook) -> untyped

  def webhook_test_items: (untyped hook, untyped triggers) -> untyped

  def test_hook_path: (untyped hook, untyped trigger) -> untyped

  def edit_hook_path: (untyped hook) -> untyped

  def destroy_hook_path: (untyped hook) -> untyped

  def hook_log_path: (untyped hook, untyped hook_log) -> untyped

  private

  def all_triggers: (untyped hook) -> untyped
end
