module NumbersHelper
  WORDS: ::Array["zero" | "one" | "two" | "three" | "four" | "five" | "six" | "seven" | "eight" | "nine"]

  def limited_counter_with_delimiter: (untyped resource, **untyped options) -> untyped

  def number_in_words: (untyped num) -> untyped
end
