module ProtectedBranchesHelper
  def protected_branch_can_admin_entity?: (untyped protected_branch_entity) -> untyped

  def protected_branch_path_by_entity: (untyped protected_branch, untyped protected_branch_entity) -> untyped
end
