module RegistrationsHelper
  def unified_registration?: () -> false

  def signup_username_data_attributes: () -> { min_length: untyped, min_length_message: untyped, max_length: untyped, max_length_message: untyped, testid: "new-user-username-field" }
end
