module SortingTitlesValuesHelper
  SORT_NAME: "name_asc"

  SORT_UPDATED_OLDEST: "updated_asc"

  SORT_UPDATED_RECENT: "updated_desc"

  # Titles.
  def sort_title_created_date: () -> untyped

  def sort_title_downvotes: () -> untyped

  def sort_title_due_date: () -> untyped

  def sort_title_due_date_later: () -> untyped

  def sort_title_due_date_soon: () -> untyped

  def sort_title_label_priority: () -> untyped

  def sort_title_merged_date: () -> untyped

  def sort_title_merged_recently: () -> untyped

  def sort_title_merged_earlier: () -> untyped

  def sort_title_closed_date: () -> untyped

  def sort_title_closed_recently: () -> untyped

  def sort_title_closed_earlier: () -> untyped

  def sort_title_largest_group: () -> untyped

  def sort_title_largest_repo: () -> untyped

  def sort_title_latest_activity: () -> untyped

  def sort_title_milestone: () -> untyped

  def sort_title_milestone_later: () -> untyped

  def sort_title_milestone_soon: () -> untyped

  def sort_title_name: () -> untyped

  def sort_title_name_asc: () -> untyped

  def sort_title_name_desc: () -> untyped

  def sort_title_oldest_activity: () -> untyped

  def sort_title_oldest_created: () -> untyped

  def sort_title_oldest_signin: () -> untyped

  def sort_title_oldest_starred: () -> untyped

  def sort_title_oldest_updated: () -> untyped

  def sort_title_popularity: () -> untyped

  def sort_title_priority: () -> untyped

  def sort_title_recently_created: () -> untyped

  def sort_title_recently_signin: () -> untyped

  def sort_title_recently_starred: () -> untyped

  def sort_title_recently_updated: () -> untyped

  def sort_title_start_date_later: () -> untyped

  def sort_title_start_date_soon: () -> untyped

  def sort_title_title: () -> untyped

  def sort_title_upvotes: () -> untyped

  def sort_title_contacted_date: () -> untyped

  def sort_title_most_stars: () -> untyped

  def sort_title_oldest_last_activity: () -> untyped

  def sort_title_recently_last_activity: () -> untyped

  def sort_title_relative_position: () -> untyped

  def sort_title_size: () -> untyped

  def sort_title_expire_date: () -> untyped

  def sort_title_relevance: () -> untyped

  # Values.
  def sort_value_created_date: () -> "created_date"

  def sort_value_downvotes: () -> "downvotes_desc"

  def sort_value_due_date: () -> "due_date"

  def sort_value_due_date_later: () -> "due_date_desc"

  def sort_value_due_date_soon: () -> "due_date_asc"

  def sort_value_label_priority: () -> "label_priority"

  def sort_value_merged_date: () -> "merged_at"

  def sort_value_merged_recently: () -> "merged_at_desc"

  def sort_value_merged_earlier: () -> "merged_at_asc"

  def sort_value_closed_date: () -> "closed_at"

  def sort_value_closed_recently: () -> "closed_at_desc"

  def sort_value_closed_earlier: () -> "closed_at_asc"

  def sort_value_largest_group: () -> "storage_size_desc"

  def sort_value_largest_repo: () -> "storage_size_desc"

  def sort_value_latest_activity: () -> "latest_activity_desc"

  def sort_value_milestone: () -> "milestone"

  def sort_value_milestone_later: () -> "milestone_due_desc"

  def sort_value_milestone_soon: () -> "milestone_due_asc"

  def sort_value_name: () -> "name_asc"

  def sort_value_name_desc: () -> "name_desc"

  def sort_value_oldest_activity: () -> "latest_activity_asc"

  def sort_value_oldest_created: () -> "created_asc"

  def sort_value_oldest_signin: () -> "oldest_sign_in"

  def sort_value_oldest_updated: () -> "updated_asc"

  def sort_value_popularity: () -> "popularity"

  def sort_value_most_popular: () -> "popularity_desc"

  def sort_value_least_popular: () -> "popularity_asc"

  def sort_value_priority: () -> "priority"

  def sort_value_recently_created: () -> "created_desc"

  def sort_value_recently_signin: () -> "recent_sign_in"

  def sort_value_recently_updated: () -> "updated_desc"

  def sort_value_start_date_later: () -> "start_date_desc"

  def sort_value_start_date_soon: () -> "start_date_asc"

  def sort_value_title: () -> "title_asc"

  def sort_value_title_desc: () -> "title_desc"

  def sort_value_upvotes: () -> "upvotes_desc"

  def sort_value_contacted_date: () -> "contacted_asc"

  def sort_value_stars_desc: () -> "stars_desc"

  def sort_value_oldest_last_activity: () -> "last_activity_on_asc"

  def sort_value_recently_last_activity: () -> "last_activity_on_desc"

  def sort_value_relative_position: () -> "relative_position"

  def sort_value_size: () -> "size_desc"

  def sort_value_expire_date: () -> "expired_asc"

  def sort_value_relevance: () -> "relevance"
end
