module TimeHelper
  TIME_UNIT_TRANSLATION: { seconds: untyped, minutes: untyped, hours: untyped, days: untyped, weeks: untyped, months: untyped, years: untyped }

  def time_interval_in_words: (untyped interval_in_seconds) -> untyped

  def time_in_milliseconds: () -> untyped
end
