module TrackingHelper
  def tracking_attrs: (untyped label, untyped action, untyped property) -> { data: { track_label: untyped, track_action: untyped, track_property: untyped } }

  def tracking_attrs_data: (untyped label, untyped action, untyped property) -> untyped
end
