module Keys
  class BaseService
    @user: untyped

    @params: untyped

    @ip_address: untyped

    attr_accessor user: untyped

    attr_accessor params: untyped

    def initialize: (untyped user, ?::Hash[untyped, untyped] params) -> void

    def notification_service: () -> untyped

    def todo_service: () -> untyped
  end
end
