module Namespaces
  class StatisticsRefresherService
    RefresherError: untyped

    def execute: (untyped root_namespace) -> untyped

    private

    def find_or_create_root_storage_statistics: (untyped root_namespace_id) -> untyped
  end
end
