module Gitlab
  module GithubImport
    module Representation
      class ProtectedBranch
        @attributes: untyped

        include Representable

        # Builds a Branch Protection info from a GitHub API response.
        # Resource structure details:
        # https://docs.github.com/en/rest/branches/branch-protection#get-branch-protection
        # branch_protection - An instance of `Hash` containing the protection details.
        def self.from_api_response: (untyped branch_protection, ?::Hash[untyped, untyped] _additional_object_data) -> untyped

        # Builds a new Protection using a Hash that was built from a JSON payload.
        def self.from_json_hash: (untyped raw_hash) -> untyped

        # attributes - A Hash containing the raw Protection details. The keys of this
        #              Hash (and any nested hashes) must be symbols.
        def initialize: (untyped attributes) -> void

        def github_identifiers: () -> { id: untyped }
      end
    end
  end
end
