module Types
  module Ci
    module Inputs
      # rubocop:disable Graphql/AuthorizeTypes -- authorized by parent Ci::Inputs::SpecType
      class ConditionType < BaseObject
      end
    end
  end
end
