module Gitlab
  module Search
    class RecentWikiPages < RecentItems
      private

      def type: () -> untyped

      def finder: () -> untyped

      def match_title: (untyped items, untyped term) -> untyped
    end
  end
end
