module Banzai
  module Filter
    module References
      class AlertReferenceFilter < IssuableReferenceFilter
        def object_sym: () -> :alert

        def parent_records: (untyped parent, untyped ids) -> untyped

        def url_for_object: (untyped alert, untyped project) -> untyped
      end
    end
  end
end
