module Banzai
  module Filter
    module References
      class IssuableReferenceFilter < AbstractReferenceFilter
        def record_identifier: (untyped record) -> untyped

        def find_object: (untyped parent, untyped iid) -> untyped
      end
    end
  end
end
