module Projects
  module Aws
    class BaseController < Projects::ApplicationController
      def admin_project_aws!: () -> (nil | untyped)

      def feature_flag_enabled!: () -> (nil | untyped)

      def track_event: (untyped action, ?untyped? label) -> untyped
    end
  end
end
