module Types
  module Ci
    # This inteface sets [authorize: :read_pipeline] (field-level authorization
    # via PipelineBaseField) for all defined fields to ensure implementing types
    # don't expose inherited fields without proper authorization.
    #
    # Implementing types can opt-out from this field-level auth and use
    # type-level auth by re-defining the field without the authorize argument.
    # For example, PipelineType uses :read_pipeline type-level auth and
    # redefines all fields in this interface to opt-out while
    # PipelineMinimalAccessType uses :read_pipeline_metadata type-level auth to
    # expose a set of defined fields and leaves inherited fields it does not
    # want to expose to use field-level auth using :read_pipeline.
    module PipelineInterface
      include BaseInterface

      def self.resolve_type: (untyped _object, untyped _context) -> untyped

      def commit: () -> untyped

      def path: () -> untyped
    end
  end
end
