module Types
  module Ci
    class PipelineScopeEnum < BaseEnum
      SCOPES_DESCRIPTION: { running: "Pipeline is running.", pending: "Pipeline has not started running yet.", finished: "Pipeline has completed.", branches: "Branches.", tags: "Tags." }
    end
  end
end
