module Projects
  module GoogleCloud
    class ConfigurationController < Projects::GoogleCloud::BaseController
      @js_data: untyped

      def index: () -> untyped

      private

      def gcp_regions: () -> untyped

      def revoke_oauth_url: () -> untyped
    end
  end
end
