module Gitlab
  module Template
    class DockerfileTemplate < BaseTemplate
      def description: () -> "# This file is a template, and might need editing before it works on your project."

      def self.extension: () -> ".Dockerfile"

      def self.categories: () -> { "General" => "" }

      def self.base_dir: () -> untyped

      def self.finder: (?untyped? project) -> untyped
    end
  end
end
