module BulkImports
  module PathNormalization
    private

    def normalize_path: (untyped path) -> untyped

    def delete_invalid_edge_characters: (untyped path) -> untyped

    def delete_invalid_multiple_characters: (untyped path) -> untyped
  end
end
