module Integrations
  module SlackMattermostNotifier
    private

    def notify: (untyped message, untyped opts) -> untyped

    class HTTPClient
      def self.post: (untyped uri, ?::Hash[untyped, untyped] params) -> untyped
    end
  end
end
