module Todos
  module Destroy
    # Service class for deleting todos that belongs to a deleted/archived design.
    class DesignService
      @design_ids: untyped

      attr_reader design_ids: untyped

      def initialize: (untyped design_ids) -> void

      def execute: () -> untyped

      private

      def todos: () -> untyped

      def deleted_designs: () -> untyped
    end
  end
end
