module AppConfig
  class InstanceMetadata
    @version: untyped

    @revision: untyped

    @kas: untyped

    @enterprise: untyped

    attr_reader version: untyped

    attr_reader revision: untyped

    attr_reader kas: untyped

    attr_reader enterprise: untyped

    def initialize: (?version: untyped, ?revision: untyped, ?enterprise: untyped) -> void
  end
end
