module Gitlab
  module Ci
    module Pipeline
      module Chain
        class CancelPendingPipelines < Chain::Base
          def perform!: () -> untyped

          def break?: () -> false

          private

          def cancellation_worker_class: () -> untyped
        end
      end
    end
  end
end
