module Gitlab
  module Ci
    module Pipeline
      module Chain
        class CreateCrossDatabaseAssociations < Chain::Base
          def perform!: () -> nil

          def break?: () -> false
        end
      end
    end
  end
end
