module Gitlab
  module Ci
    module Pipeline
      module Chain
        class RemoveUnwantedChatJobs < Chain::Base
          def perform!: () -> (nil | untyped)

          def break?: () -> false
        end
      end
    end
  end
end
