module Deployments
  class UpdateService
    @deployment: untyped

    @params: untyped

    attr_reader deployment: untyped

    attr_reader params: untyped

    def initialize: (untyped deployment, untyped params) -> void

    def execute: () -> untyped
  end
end
