module CloudSeed
  module GoogleCloud
    class EnableCloudsqlService < ::CloudSeed::GoogleCloud::BaseService
      def execute: () -> untyped

      private

      def ci_var_protected?: () -> untyped
    end
  end
end
