module Projects
  class AllBranchesRule < BranchRule
    include Projects::CustomBranchRule

    def name: () -> untyped

    def matching_branches_count: () -> untyped

    def squash_option: () -> untyped
  end
end
