module Projects
  class TriggeredHooks
    @scope: untyped

    @data: untyped

    @relations: untyped

    def initialize: (untyped scope, untyped data) -> void

    def add_hooks: (untyped relation) -> self

    def execute: () -> untyped
  end
end
