module Gitlab
  module ImportExport
    class AvatarSaver
      @project: untyped

      @shared: untyped

      include DurationMeasuring

      def initialize: (project: untyped, shared: untyped) -> void

      def save: () -> untyped
    end
  end
end
