module Gitlab
  module ImportExport
    class HashUtil
      def self.deep_symbolize_array!: (untyped array) ?{ (untyped) -> untyped } -> (nil | untyped)

      def self.deep_symbolize_array_with_date!: (untyped array) -> untyped
    end
  end
end
