module Gitlab
  module ImportExport
    class SnippetRepoSaver < RepoSaver
      @project: untyped

      @shared: untyped

      @repository: untyped

      def initialize: (project: untyped, shared: untyped, repository: untyped) -> void

      private

      def bundle_full_path: () -> untyped
    end
  end
end
