module Gitlab
  module ImportExport
    class VersionChecker
      @shared: untyped

      def self.check!: (*untyped args, **untyped kwargs) -> untyped

      def initialize: (shared: untyped) -> void

      def check!: () -> untyped

      private

      def version_file: () -> untyped

      def verify_version!: (untyped version) -> (untyped | true)

      def different_version?: (untyped version) -> untyped
    end
  end
end
