module API
  module Helpers
    module WorkItems
      module WidgetValidation
        def validate_supported_widgets!: (untyped work_item_type, untyped resource_parent, untyped widget_params) -> (nil | untyped)

        def strip_disabled_widget_params!: (untyped widget_params, untyped work_item_type, untyped resource_parent) -> untyped
      end
    end
  end
end
