module Boards
  class CreateService < Boards::BaseService
    include Gitlab::InternalEvents::ServiceTracking

    def execute: () -> untyped

    private

    def can_create_board?: () -> untyped

    def create_board!: () -> untyped

    def parent_board_collection: () -> untyped
  end
end
