module WorkItems
  module DataSync
    module Widgets
      class AwardEmoji < Base
        def after_create: () -> (nil | untyped)

        def post_move_cleanup: () -> untyped

        private

        def new_work_item_award_emoji: (untyped awards_batch) -> untyped
      end
    end
  end
end
