module WorkItems
  module DataSync
    module Widgets
      class CurrentUserTodos < Base
        def after_save_commit: () -> nil

        def post_move_cleanup: () -> nil
      end
    end
  end
end
