#
# Handles support for WebAuthn analytics instrumentation in controllers
#
module Authn
  module WebauthnInstrumentation
    extend ActiveSupport::Concern

    include Gitlab::InternalEventsTracking

    PASSKEY_EVENT_TRACKING_STATUS: { 0 => "attempt", 1 => "success", 2 => "failure" }

    PASSKEY_EVENT_TRACKING_ENTRY_POINT: { 1 => "two_factor_page", 2 => "password_page", 3 => "two_factor_after_login_page", 4 => "passwordless_passkey_button" }

    # Tracks a WebAuthn internal event
    #
    # Requires event_name(string), status(int)
    #
    # Optional: entry_point(int), user(object)
    #
    def track_passkey_internal_event: (event_name: untyped, status: untyped, ?entry_point: untyped?, ?user: untyped?) -> (nil | untyped)

    private

    def passkey_track_event_additional_properties: (?status: untyped?, ?entry_point: untyped?, ?user: untyped?) -> { status: untyped, entry_point: untyped, browser: untyped, device_type: untyped, device_name: untyped, has_2fa: untyped }
  end
end
