module Gitlab
  module Database
    module MigrationHelpers
      module V2
        include Gitlab::Database::MigrationHelpers

        # Creates a new table, optionally allowing the caller to add text limit constraints to the table.
        # This method only extends Rails' `create_table` method
        #
        # Example:
        #
        #    create_table :db_guides do |t|
        #      t.bigint :stars, default: 0, null: false
        #      t.text :title, limit: 128
        #      t.text :notes, limit: 1024
        #
        #      t.check_constraint 'stars > 1000', name: 'so_many_stars'
        #    end
        #
        # See Rails' `create_table` for more info on the available arguments.
        #
        # When adding foreign keys to other tables, consider wrapping the call into a with_lock_retries block
        # to avoid traffic stalls.
        def create_table: (untyped table_name, *untyped args, **untyped kwargs) { (untyped) -> untyped } -> untyped

        # Executes the block with a retry mechanism that alters the +lock_timeout+ and +sleep_time+ between attempts.
        # The timings can be controlled via the +timing_configuration+ parameter.
        # If the lock was not acquired within the retry period, a last attempt is made without using +lock_timeout+.
        #
        # In order to retry the block, the method wraps the block into a transaction.
        #
        # When called inside an open transaction it will execute the block directly.
        #
        # ==== Examples
        #   # Invoking without parameters
        #   with_lock_retries do
        #     drop_table :my_table
        #   end
        #
        #   # Invoking with custom +timing_configuration+
        #   t = [
        #     [1.second, 1.second],
        #     [2.seconds, 2.seconds]
        #   ]
        #
        #   with_lock_retries(timing_configuration: t) do
        #     drop_table :my_table # this will be retried twice
        #   end
        #
        #   # Disabling the retries using an environment variable
        #   > export DISABLE_LOCK_RETRIES=true
        #
        #   with_lock_retries do
        #     drop_table :my_table # one invocation, it will not retry at all
        #   end
        #
        # ==== Parameters
        # * +timing_configuration+ - [[ActiveSupport::Duration, ActiveSupport::Duration], ...] lock timeout for the block, sleep time before the next iteration, defaults to `Gitlab::Database::WithLockRetries::DEFAULT_TIMING_CONFIGURATION`
        # * +logger+ - [Gitlab::JsonLogger]
        # * +env+ - [Hash] custom environment hash, see the example with `DISABLE_LOCK_RETRIES`
        def with_lock_retries: (*untyped args, **untyped kwargs) { () -> untyped } -> untyped

        # Renames a column without requiring downtime.
        #
        # Concurrent renames work by using database triggers to ensure both the
        # old and new column are in sync. However, this method will _not_ remove
        # the triggers or the old column automatically; this needs to be done
        # manually in a post-deployment migration. This can be done using the
        # method `cleanup_concurrent_column_rename`.
        #
        # table - The name of the database table containing the column.
        # old_column - The old column name.
        # new_column - The new column name.
        # type - The type of the new column. If no type is given the old column's
        #        type is used.
        # batch_column_name - option is for tables without primary key, in this
        #        case another unique integer column can be used. Example: :user_id
        def rename_column_concurrently: (untyped table, untyped old_column, untyped new_column, ?type: untyped?, ?batch_column_name: ::Symbol, ?type_cast_function: untyped?) -> untyped

        # Reverses operations performed by rename_column_concurrently.
        #
        # This method takes care of removing previously installed triggers as well
        # as removing the new column.
        #
        # table - The name of the database table.
        # old_column - The name of the old column.
        # new_column - The name of the new column.
        def undo_rename_column_concurrently: (untyped table, untyped old_column, untyped new_column) -> untyped

        # Cleans up a concurrent column name.
        #
        # This method takes care of removing previously installed triggers as well
        # as removing the old column.
        #
        # table - The name of the database table.
        # old_column - The name of the old column.
        # new_column - The name of the new column.
        def cleanup_concurrent_column_rename: (untyped table, untyped old_column, untyped new_column) -> untyped

        # Reverses the operations performed by cleanup_concurrent_column_rename.
        #
        # This method adds back the old_column removed
        # by cleanup_concurrent_column_rename.
        # It also adds back the triggers that are removed
        # by cleanup_concurrent_column_rename.
        #
        # table - The name of the database table containing the column.
        # old_column - The old column name.
        # new_column - The new column name.
        # type - The type of the old column. If no type is given the new column's
        #        type is used.
        # batch_column_name - option is for tables without primary key, in this
        #        case another unique integer column can be used. Example: :user_id
        #
        def undo_cleanup_concurrent_column_rename: (untyped table, untyped old_column, untyped new_column, ?type: untyped?, ?batch_column_name: ::Symbol) -> untyped

        # TRUNCATE is a DDL statement (it drops the table and re-creates it), so we want to run the
        # migration in DDL mode, but we also don't want to execute it against all schemas because
        # it will be prevented by the lock_writes trigger.
        #
        # For example,
        # a `gitlab_main` table on `:gitlab_main` database will be truncated,
        # and a `gitlab_main` table on `:gitlab_ci` database will be skipped.
        #
        # Note Rails already has a truncate_tables, see
        # https://github.com/rails/rails/blob/6-1-stable/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb#L193
        def truncate_tables!: (*untyped table_names, ?connection: untyped) -> (nil | untyped)

        # Rename an index that exists in a different schema other than current_schema() `public`,
        # for example, an index under schema `gitlab_partitions_dynamic`
        #
        # table_name - The table name that old_index_name is under,
        #               e.g. `gitlab_partitions_dynamic.ci_builds_101` or `ci_builds`
        #               schema name in the table name will be used unless the `schema` argument is given
        # schema - The schema name that old_index_name is under
        def rename_index_with_schema: (untyped table_name, untyped old_index_name, untyped new_index_name, ?schema: untyped?) -> untyped

        private

        def setup_renamed_column: (untyped calling_operation, untyped table, untyped old_column, untyped new_column, type: untyped, batch_column_name: untyped, ?type_cast_function: untyped?) -> untyped

        def teardown_rename_mechanism: (untyped table, untyped old_column, untyped new_column, column_to_remove: untyped) -> (nil | untyped)

        def install_bidirectional_triggers: (untyped table, untyped old_column, untyped new_column) -> untyped

        def remove_bidirectional_triggers: (untyped table, untyped old_column, untyped new_column) -> untyped

        def bidirectional_trigger_names: (untyped table, untyped old_column, untyped new_column) -> untyped

        def function_name_for_trigger: (untyped trigger_name) -> ::String

        def create_insert_trigger: (untyped trigger_name, untyped quoted_table, untyped quoted_old_column, untyped quoted_new_column) -> untyped

        def create_update_trigger: (untyped trigger_name, untyped quoted_table, untyped quoted_source_column, untyped quoted_target_column) -> untyped

        def drop_trigger: (untyped trigger_name, untyped quoted_table) -> untyped
      end
    end
  end
end
