module API
  module Entities
    class User < UserBasic
      include ::UsersHelper

      include TimeZoneHelper

      include Gitlab::Utils::StrongMemoize

      def following_users_allowed: (untyped current_user, untyped user) -> untyped
    end
  end
end
