module Gitlab
  module HTTP_V2
    BlockedUrlError: untyped

    RedirectionTooDeep: untyped

    ReadTotalTimeout: untyped

    HeaderReadTimeout: untyped

    SilentModeBlockedError: untyped

    ResponseSizeTooLarge: untyped

    MaxDecompressionSizeError: untyped

    InvalidResponseError: untyped

    HeaderInjectionError: untyped

    HTTP_TIMEOUT_ERRORS: ::Array[untyped]

    HTTP_ERRORS: untyped
  end
end
