module ContainerRegistry
  module Protection
    class CreateRuleService < BaseProjectService
      include ContainerRegistry::Protection::InternalEventsTracking

      ALLOWED_ATTRIBUTES: ::Array[:repository_path_pattern | :minimum_access_level_for_push | :minimum_access_level_for_delete]

      def execute: () -> untyped

      private

      def service_response_error: (message: untyped) -> untyped
    end
  end
end
