module Groups
  class UpdateStatisticsService
    @group: untyped

    @statistics: untyped

    @namespace_statistics: untyped

    attr_reader group: untyped

    attr_reader statistics: untyped

    def initialize: (untyped group, ?statistics: untyped) -> void

    def execute: () -> untyped

    private

    def namespace_statistics: () -> untyped
  end
end
