module Gitlab
  module BitbucketImport
    module Importers
      class IssueImporter
        @project: untyped

        @formatter: untyped

        @user_finder: untyped

        @mentions_converter: untyped

        @object: untyped

        include Loggable

        include ErrorTracking

        def initialize: (untyped project, untyped hash) -> void

        def execute: () -> untyped

        private

        attr_reader object: untyped

        attr_reader project: untyped

        attr_reader formatter: untyped

        attr_reader user_finder: untyped

        attr_reader mentions_converter: untyped

        def description: () -> untyped

        def author_line: () -> ("" | untyped)

        def find_user_id: () -> untyped

        def author_id: () -> untyped
      end
    end
  end
end
