module Gitlab
  module BitbucketImport
    module Importers
      class LfsObjectsImporter
        include ParallelScheduling

        def execute: () -> untyped

        private

        def sidekiq_worker_class: () -> untyped

        def collection_method: () -> :lfs_objects

        def id_for_already_enqueued_cache: (untyped object) -> untyped

        def queue_workers: (untyped download_service) -> untyped
      end
    end
  end
end
