module Gitlab
  module BitbucketImport
    module Importers
      class RepositoryImporter
        @project: untyped

        include Loggable

        LABELS: ::Array[{ title: "bug", color: "#FF0000" } | { title: "enhancement", color: "#428BCA" } | { title: "proposal", color: "#69D100" } | { title: "task", color: "#7F8C8D" }]

        def initialize: (untyped project) -> void

        def execute: () -> untyped

        private

        attr_reader project: untyped

        def refmap: () -> ::Array["+refs/pull-requests/*/to:refs/merge-requests/*/head"]

        def import_wiki: () -> untyped

        def create_labels: () -> untyped

        def wiki: () -> untyped

        def update_clone_time: () -> untyped

        def validate_repository_size!: () -> nil

        def set_default_branch: () -> untyped

        def client: () -> untyped
      end
    end
  end
end
