module Gitlab
  module GlobalId
    module Deprecations
      # Contains the deprecations in place.
      # Example:
      #
      #   DEPRECATIONS = [
      #     Gitlab::Graphql::DeprecationsBase::NameDeprecation.new(old_name: 'PrometheusService', new_name: 'Integrations::Prometheus', milestone: '14.1')
      #   ].freeze
      DEPRECATIONS: ::Array[untyped]

      def self.map_graphql_name: (untyped model_name) -> untyped

      include Gitlab::Graphql::DeprecationsBase
    end
  end
end
