module RemoteMirrors
  class UpdateService < BaseService
    def execute: (untyped remote_mirror) -> untyped

    private

    def allowed_attributes: () -> untyped

    def allowed?: () -> untyped
  end
end
