module Gitlab
  module Database
    module Aggregation
      module ActiveRecord
        class DimensionDefinition < PartDefinition
          @association: untyped

          attr_reader association: untyped

          def initialize: (*untyped args, ?association: bool, **untyped kwargs) -> void

          def association?: () -> untyped

          def to_arel: (untyped context) -> untyped
        end
      end
    end
  end
end
