module Ml
  module ModelVersions
    class GetModelVersionService
      @project: untyped

      @name: untyped

      @version: untyped

      def initialize: (untyped project, untyped name, untyped version) -> void

      def execute: () -> untyped
    end
  end
end
