module ActiveRecord
  module GitlabPatches
    module Partitioning
      module Reflection
        module AssociationReflection
          def check_eager_loadable!: () -> (nil | untyped)
        end
      end
    end
  end
end
