module Pajamas
  module Concerns
    module CheckboxRadioLabelWithHelpText
      def render_label_with_help_text: () -> untyped

      def render_label_tag_with_help_text: () -> untyped

      private

      def label_entry: () -> untyped

      def formatted_label_options: () -> untyped
    end
  end
end
