module Analytics
  module CycleAnalytics
    module Stages
      class ListService < Analytics::CycleAnalytics::Stages::BaseService
        def execute: () -> untyped

        private

        def allowed?: () -> untyped

        def success: (untyped stages) -> untyped

        def filter_by_stage_ids?: () -> untyped
      end
    end
  end
end
