module Integrations
  module HarborSerializers
    class RepositoryEntity < Grape::Entity
      include ActionView::Helpers::SanitizeHelper

      private

      def validate_path: (untyped path) -> untyped
    end
  end
end
