module Ci
  module NamespaceSettings
    class UpdateService
      @settings: untyped

      @args: untyped

      def initialize: (untyped settings, untyped args) -> void

      def execute: () -> untyped

      private

      attr_accessor args: untyped

      attr_accessor settings: untyped
    end
  end
end
