module Gitlab
  module Email
    class SmtpConfig
      @secrets: untyped

      def self.encrypted_secrets: () -> untyped

      def self.secrets: () -> untyped

      def initialize: () -> void

      def username: () -> untyped

      def password: () -> untyped
    end
  end
end
