module Sidebars
  module UserSettings
    module Menus
      class PreferencesMenu < ::Sidebars::Menu
        include ::Sidebars::Concerns::RenderIfLoggedIn

        def link: () -> untyped

        def title: () -> untyped

        def sprite_icon: () -> "preferences"

        def active_routes: () -> { controller: :preferences }
      end
    end
  end
end
