module BatchedBackgroundMigration
  class BatchedBackgroundMigrationGenerator < ActiveRecord::Generators::Base
    def validate!: () -> untyped

    def create_post_migration_and_specs: () -> untyped

    def create_batched_background_migration_class_and_specs: () -> untyped

    def create_dictionary_file: () -> untyped

    def db_migrate_path: () -> untyped

    private

    def table_name: () -> untyped

    def column_name: () -> untyped

    def feature_category: () -> untyped

    def ee_only?: () -> untyped

    def current_milestone: () -> untyped
  end
end
