class AwardEmojiPresenter < Gitlab::View::Presenter::Delegated
  @emoji: untyped

  def description: () -> untyped

  def unicode: () -> untyped

  def emoji: () -> untyped

  def unicode_version: () -> untyped

  private

  def as_emoji: () -> untyped
end
