class InstanceClusterablePresenter < ClusterablePresenter
  extend ::Gitlab::Utils::Override

  def self.fabricate: (untyped clusterable, **untyped attributes) -> untyped

  def index_path: (?::Hash[untyped, untyped] options) -> untyped

  def cluster_status_cluster_path: (untyped cluster, ?::Hash[untyped, untyped] params) -> untyped

  def create_cluster_migration_path: (untyped cluster) -> untyped

  def update_cluster_migration_path: (untyped cluster) -> untyped

  def clear_cluster_cache_path: (untyped cluster) -> untyped

  def cluster_path: (untyped cluster, ?::Hash[untyped, untyped] params) -> untyped

  def connect_path: () -> untyped

  def new_cluster_docs_path: () -> nil

  def create_user_clusters_path: () -> untyped

  def empty_state_help_text: () -> untyped

  def sidebar_text: () -> untyped

  def learn_more_link: () -> untyped
end
