module Gitlab
  module Prometheus
    class Internal
      def self.uri: () -> (nil | untyped)

      def self.server_address: () -> untyped

      def self.prometheus_enabled?: () -> untyped
    end
  end
end
