module Gitlab
  module WordDiff
    class ChunkCollection
      @chunks: untyped

      def initialize: () -> void

      def add: (untyped chunk) -> untyped

      def content: () -> untyped

      def reset: () -> untyped

      def marker_ranges: () -> untyped

      private

      def mode_for_element: (untyped element) -> (untyped | nil)
    end
  end
end
