module Gitlab
  module Import
    module UsernameMentionRewriter
      MENTION_REGEX: untyped

      def update_username_mentions: (untyped relation_hash) -> untyped

      def wrap_mentions_in_backticks: (untyped text) -> untyped
    end
  end
end
