module BlobViewer
  class RouteMap < Base
    @validation_message: untyped

    include ServerSide

    include Auxiliary

    def validation_message: () -> untyped

    def valid?: () -> untyped
  end
end
