module BitbucketServer
  module Representation
    # An inline comment with the following structure that identifies
    # the part of the diff:
    #
    # "commentAnchor": {
    #   "diffType": "EFFECTIVE",
    #   "fileType": "TO",
    #   "fromHash": "c5f4288162e2e6218180779c7f6ac1735bb56eab",
    #   "line": 1,
    #   "lineType": "ADDED",
    #   "orphaned": false,
    #   "path": "CHANGELOG.md",
    #   "toHash": "a4c2164330f2549f67c13f36a93884cf66e976be"
    #  }
    #
    # More details in https://docs.atlassian.com/bitbucket-server/rest/5.12.0/bitbucket-rest.html.
    class PullRequestComment < Comment
      @line_position: untyped

      def from_sha: () -> untyped

      def to_sha: () -> untyped

      def to?: () -> untyped

      def from?: () -> untyped

      def added?: () -> untyped

      def removed?: () -> untyped

      # There are three line comment types: added, removed, or context.
      #
      # 1. An added type means a new line was inserted, so there is no old position.
      # 2. A removed type means a line was removed, so there is no new position.
      # 3. A context type means the line was unmodified, so there is both a
      #    old and new position.
      def new_pos: () -> (nil | untyped)

      def old_pos: () -> (nil | untyped)

      def file_path: () -> untyped

      def to_hash: () -> untyped

      private

      def file_type: () -> untyped

      def line_type: () -> untyped

      # Each comment contains the following information about the diff:
      #
      # hunks: [
      #     {
      #         segments: [
      #             {
      #                 "lines": [
      #                     {
      #                         "commentIds": [ N ],
      #                         "source": X,
      #                         "destination": Y
      #                     }, ...
      #                   ] ....
      #
      # To determine the line position of a comment, we search all the lines
      # entries until we find this comment ID.
      def line_position: () -> untyped

      def comment_anchor: () -> untyped

      def diff: () -> untyped

      def diff_hunks: () -> untyped
    end
  end
end
