module Layouts
  class SettingsSectionComponent < ViewComponent::Base
    @heading: untyped

    @description: untyped

    @id: untyped

    @testid: untyped

    @options: untyped

    # @param [String] heading
    # @param [String] description
    # @param [String] id
    # @param [String] testid
    # @param [Hash] options
    def initialize: (untyped heading, ?description: untyped?, ?id: untyped?, ?testid: untyped?, ?options: ::Hash[untyped, untyped]) -> void

    def options_attrs: () -> untyped
  end
end
