module Authn
  module Tokens
    class RunnerAuthenticationToken
      @revocable: untyped

      @source: untyped

      LEGACY_RUNNER_PARTITION_PREFIXES: ::Array["t1_" | "t2_" | "t3_"]

      def self.prefix?: (untyped plaintext) -> untyped

      attr_reader revocable: untyped

      attr_reader source: untyped

      def initialize: (untyped plaintext, untyped source) -> void

      def present_with: () -> untyped

      def revoke!: (untyped current_user) -> untyped
    end
  end
end
