module Gitlab
  module SlashCommands
    module Presenters
      class Deploy < Presenters::Base
        def present: (untyped from, untyped to) -> untyped

        def action_not_found: () -> untyped
      end
    end
  end
end
