module Gitlab
  module SlashCommands
    module Presenters
      class Error < Presenters::Base
        @message: untyped

        def initialize: (untyped message) -> void

        def message: () -> untyped
      end
    end
  end
end
