module Gitlab
  module SlashCommands
    module Presenters
      class IssueSearch < Presenters::Base
        @project: untyped

        include Presenters::IssueBase

        def present: () -> untyped

        private

        def attachments: () -> untyped

        def project: () -> untyped
      end
    end
  end
end
