module Sidebars
  module Organizations
    module Menus
      class ScopeMenu < ::Sidebars::Menu
        def link: () -> untyped

        def title: () -> untyped

        def active_routes: () -> { path: "organizations/organizations#show" }

        def render?: () -> true

        def serialize_as_menu_item_args: () -> untyped
      end
    end
  end
end
