module API
  module Validations
    module Types
      class WorkhorseFile
        def self.parse: (untyped value) -> (nil | untyped)

        def self.parsed?: (untyped value) -> untyped
      end
    end
  end
end
