# Service Ping payload build using the instrumentation classes
# for given metrics key_paths and output method
module Gitlab
  module Usage
    module ServicePing
      class InstrumentedPayload
        @metrics_key_paths: untyped

        @output_method: untyped

        attr_reader metrics_key_paths: untyped

        attr_reader output_method: untyped

        def initialize: (untyped metrics_key_paths, untyped output_method) -> void

        def build: () -> untyped

        private

        # Not all metrics definitions have instrumentation classes
        # The value can be computed only for those that have it
        def instrumented_metrics_defintions: () -> untyped

        def compute_instrumental_value: (untyped key_path, untyped output_method) -> untyped

        def metric_fallback: (untyped key_path) -> untyped
      end
    end
  end
end
