module Projects
  module CustomBranchRule
    @project: untyped

    extend ActiveSupport::Concern

    def initialize: (untyped project) -> void

    def name: () -> untyped

    def matching_branches_count: () -> untyped

    def default_branch?: () -> false

    def protected?: () -> false

    def branch_protection: () -> nil

    def group: () -> nil

    def squash_option: () -> nil

    def created_at: () -> nil

    def updated_at: () -> nil
  end
end
