class MetricsController < BaseActionController
  @metrics_service: untyped

  include RequiresAllowlistedMonitoringClient

  def index: () -> untyped

  def system: () -> untyped

  private

  def metrics_service: () -> untyped

  def system_metrics: () -> untyped
end
