class SentNotificationsController < ApplicationController
  @notification_id_from_request: untyped

  extend ::Gitlab::Utils::Override

  include Gitlab::Utils::StrongMemoize

  def unsubscribe: () -> untyped

  def auth_user: () -> untyped

  private

  def sent_notification: () -> untyped

  def unsubscribe_prerequisites_met?: () -> untyped

  def noteable: () -> untyped

  def unsubscribe_and_redirect: () -> untyped

  def unsubscribe_issue_email_participant: () -> (nil | untyped)

  def noteable_path: (untyped noteable) -> untyped

  def render_expired_link: () -> untyped
end
