module Ci
  module ExternalPullRequests
    class CreatePipelineService < BaseService
      def execute: (untyped pull_request) -> untyped

      private

      def pull_request_not_open_error: () -> untyped

      def pull_request_branch_error: () -> untyped
    end
  end
end
