module Gitlab
  module BackgroundMigration
    # rubocop:disable Migration/BatchedMigrationBaseClass -- BackfillOccurrenceIdToVulnerabilityAssociations is a subclass
    # of BatchedMigrationJob
    class BackfillOccurrenceIdToExternalIssueLinks < BackfillOccurrenceIdToVulnerabilityAssociations
    end
  end
end
