module Gitlab
  module BackgroundMigration
    class BackfillServiceAccountIdOnDuoWorkflowsWorkflows < BatchedMigrationJob
      def perform: () -> untyped

      private

      def backfill_service_account_id: (untyped id_sub_batch) -> untyped

      def backfill_sql: (untyped id_sub_batch) -> ::String
    end
  end
end
