module Gitlab
  module BackgroundMigration
    class BackfillCommitUserMentionsNamespaceId < BatchedMigrationJob
      TABLE_NAME: :commit_user_mentions

      FOREIGN_KEY: :note_id

      def perform: () -> untyped

      private

      def build_update_query: (untyped sub_batch) -> ::String

      def namespace_relation_subquery: () -> ::String

      def update_statement: () -> ::String
    end
  end
end
