module Gitlab
  module BackgroundMigration
    # rubocop:disable Metrics/ClassLength -- Backfilling from multiple sources increases the length
    class FixNamespaceState < BatchedMigrationJob
      # Subset of namespace state enum values used by this migration (archive/deletion related only)
      STATES: { ancestor_inherited: 0, archived: 1, deletion_scheduled: 2, deletion_in_progress: 4 }

      PRESERVE_EVENTS: { deletion_scheduled: "schedule_deletion" }

      def perform: () -> untyped

      private

      # rubocop:disable Metrics/MethodLength -- Need to do atomic updates
      def fix_namespace_state_and_metadata: (untyped ids_list) -> untyped
    end
  end
end
