module Gitlab
  module BackgroundMigration
    # This class is responsible for updating users external field if service account.
    class UpdateUsersSetExternalIfServiceAccount < BatchedMigrationJob
      def perform: () -> untyped
    end
  end
end
