module Clusters
  module Concerns
    module KubernetesLogger
      @logger: untyped

      def logger: () -> untyped

      def log_exception: (untyped error, untyped event) -> untyped
    end
  end
end
