# frozen_string_literal: true
module Gitlab
  module Auth
    class BlockedUserTracker
      @user: untyped

      @auth: untyped

      def initialize: (untyped user, untyped auth) -> void

      def log_activity!: () -> untyped
    end
  end
end
