module Mcp
  module Tools
    module Concerns
      module Constants
        GROUP_ONLY_TYPES: ::Array["Epic" | "Objective" | "KeyResult"]

        PROJECT_AND_GROUP_TYPES: ::Array["Issue" | "Task"]

        ALL_TYPES: untyped

        URL_PATTERNS: { work_item: ::Regexp, quick_action: ::Regexp }

        VERSIONS: { v0_1_0: "0.1.0" }
      end
    end
  end
end
