module Import
  module PlaceholderReferences
    class LoadService < BaseService
      @processed_count: untyped

      @error_count: untyped

      BATCH_LIMIT: 500

      def initialize: (import_source: untyped, import_uid: untyped) -> void

      def execute: () -> untyped

      private

      attr_accessor error_count: untyped

      attr_accessor processed_count: untyped

      def next_batch: () -> untyped

      def load!: (untyped batch) -> untyped

      def bulk_insert!: (untyped to_load) -> untyped

      def clear_batch!: (untyped batch) -> untyped

      def log_error: (untyped item, untyped exception) -> untyped
    end
  end
end
