module DevOpsReport
  class MetricPresenter < Gitlab::View::Presenter::Simple
    def cards: () -> ::Array[untyped]

    def idea_to_production_steps: () -> ::Array[untyped]

    def average_percentage_score: () -> untyped
  end
end
