module SavedReplies
  class DestroyService < BaseService
    @saved_reply: untyped

    def initialize: (saved_reply: untyped) -> void

    def execute: () -> untyped

    private

    attr_reader saved_reply: untyped
  end
end
