module SavedReplies
  class UpdateService < BaseService
    @saved_reply: untyped

    @name: untyped

    @content: untyped

    def initialize: (saved_reply: untyped, name: untyped, content: untyped) -> void

    def execute: () -> untyped

    private

    attr_reader saved_reply: untyped

    attr_reader name: untyped

    attr_reader content: untyped
  end
end
