module Sidebars
  module Groups
    module SuperSidebarMenus
      class BuildMenu < ::Sidebars::Menu
        def title: () -> untyped

        def sprite_icon: () -> "rocket"

        def configure_menu_items: () -> untyped
      end
    end
  end
end
