module Gitlab
  module GithubImport
    module Stage
      class ImportNotesWorker
        include ApplicationWorker

        include StageMethods

        def perform: (untyped _project_id) -> nil
      end
    end
  end
end
