module Gitlab
  module GithubImport
    module Stage
      class ImportLfsObjectsWorker
        include ApplicationWorker

        include StageMethods

        # project - An instance of Project.
        def import: (untyped _client, untyped project) -> untyped
      end
    end
  end
end
