# frozen_string_literal: true
module Gitlab
  module Auth
    module Otp
      module Fortinet
        private

        def forti_authenticator_enabled?: (untyped user) -> untyped

        def forti_token_cloud_enabled?: (untyped user) -> untyped
      end
    end
  end
end
