module Types
  module Security
    module CodequalityReportsComparer
      # rubocop: disable Graphql/AuthorizeTypes -- The resolver authorizes the request
      class DegradationType < BaseObject
      end
    end
  end
end
