module Terraform
  module StateProtectionRules
    class UpdateRuleService
      @protection_rule: untyped

      @current_user: untyped

      @params: untyped

      include Gitlab::Allowable

      ALLOWED_ATTRIBUTES: ::Array[:state_name | :minimum_access_level_for_write | :allowed_from]

      def initialize: (untyped protection_rule, current_user: untyped, ?params: ::Hash[untyped, untyped]) -> void

      def execute: () -> untyped

      private

      attr_reader protection_rule: untyped

      attr_reader current_user: untyped

      attr_reader params: untyped

      def service_response_error: (message: untyped) -> untyped
    end
  end
end
