module Groups
  class AchievementsController < Groups::ApplicationController
    def new: () -> untyped

    def edit: () -> untyped

    private

    def authorize_read_achievement!: () -> (untyped | nil)

    def authorize_admin_achievement!: () -> (untyped | nil)
  end
end
