module Groups
  class PackagesController < Groups::ApplicationController
    def index: () -> nil

    # The show action renders index to allow frontend routing to work on page refresh
    def show: () -> untyped

    private

    def verify_packages_enabled!: () -> (untyped | nil)
  end
end
