module BulkImports
  module Pipeline
    module IndexCacheStrategy
      def already_processed?: (untyped _, untyped index) -> untyped

      def save_processed_entry: (untyped _, untyped index) -> untyped
    end
  end
end
