module Ci
  module JobArtifacts
    class DeleteService
      @build: untyped

      include BaseServiceUtility

      def initialize: (untyped build) -> void

      def execute: () -> untyped

      private

      attr_reader build: untyped
    end
  end
end
