class Import::GiteaController < Import::GithubController
  @client_repos: untyped

  @client: untyped

  @verified_url_and_hostname: untyped

  extend ::Gitlab::Utils::Override

  def new: () -> (untyped | nil)

  def personal_access_token: () -> untyped

  def status: () -> untyped

  def provider_name: () -> :gitea

  private

  def host_key: () -> ::Symbol

  def provider_url: () -> untyped

  def logged_in_with_provider?: () -> false

  def provider_auth: () -> (untyped | nil)

  def serialized_imported_projects: (?untyped projects) -> untyped

  def client_repos: () -> untyped

  def client: () -> untyped

  def client_options: () -> { host: untyped, api_version: "v1", hostname: untyped }

  def verify_blocked_uri: () -> untyped
end
