module Import
  class SourceUsersController < ApplicationController
    def accept: () -> untyped

    def decline: () -> untyped

    def show: () -> nil

    private

    def check_source_user_valid!: () -> (nil | untyped)

    def current_user_matches_invite?: () -> untyped

    def source_user: () -> untyped

    def banner: (untyped partial) -> untyped
  end
end
