class JoinedGroupsFinder
  @user: untyped

  def initialize: (untyped user) -> void

  # Finds the groups of the source user, optionally limited to those visible to
  # the current user.
  def execute: (?untyped? current_user) -> untyped
end
