module Sidebars
  module YourWork
    module Menus
      class ProjectsMenu < ::Sidebars::Menu
        def link: () -> untyped

        def title: () -> untyped

        def sprite_icon: () -> "project"

        def render?: () -> untyped

        def active_routes: () -> ({ controller: ::Array["projects" | "dashboard/projects"] } | { controller: ::Array["root" | "projects" | "dashboard/projects"] })
      end
    end
  end
end
