module Gitlab
  module Git
    module Conflict
      class Resolution
        @user: untyped

        @files: untyped

        @commit_message: untyped

        attr_reader user: untyped

        attr_reader files: untyped

        attr_reader commit_message: untyped

        def initialize: (untyped user, untyped files, untyped commit_message) -> void
      end
    end
  end
end
