module WorkItems
  module Callbacks
    class CurrentUserTodos < Base
      def before_update: () -> (nil | untyped)

      private

      def add_todo: () -> (nil | untyped)

      def mark_as_done: (untyped todo_id) -> (nil | untyped)
    end
  end
end
