module Gitlab
  module Database
    module SchemaMigrations
      class Migrations
        @context: untyped

        @version_filenames: untyped

        MIGRATION_VERSION_GLOB: "20[0-9][0-9]*"

        def initialize: (untyped context) -> void

        def touch_all: () -> (nil | untyped)

        def load_all: () -> (nil | untyped)

        private

        def schema_directory: () -> untyped

        def version_filenames: () -> untyped
      end
    end
  end
end
