module Gitlab
  module Ci
    class Config
      module Entry
        #
        # Common validations and behavior for input definitions in CI configuration.
        # Used by JobInput (job-level inputs) and Header::Input (spec-level inputs).
        module BaseInput
          extend ActiveSupport::Concern

          COMMON_ALLOWED_KEYS: ::Array[:default | :description | :options | :regex | :type]

          ALLOWED_OPTIONS_LIMIT: 50

          def value: () -> untyped
        end
      end
    end
  end
end
