module Gitlab
  module Ci
    class Config
      module Entry
        #
        # Entry that represents Coverage settings.
        #
        class Coverage < ::Gitlab::Config::Entry::Node
          include ::Gitlab::Config::Entry::Validatable

          def value: () -> untyped
        end
      end
    end
  end
end
