module Gitlab
  module Ci
    class Config
      module Entry
        #
        # Entry that represents a JWT definition.
        #
        class IdToken < ::Gitlab::Config::Entry::Node
          include ::Gitlab::Config::Entry::Attributable

          include ::Gitlab::Config::Entry::Validatable

          def value: () -> { aud: untyped }
        end
      end
    end
  end
end
