module Gitlab
  module Ci
    class Config
      module Entry
        #
        # Entry that represents a configuration of the pull policies of an image.
        #
        class PullPolicy < ::Gitlab::Config::Entry::Node
          include ::Gitlab::Config::Entry::Validatable

          ALLOWED_POLICIES: ::Array["always" | "never" | "if-not-present"]

          def value: () -> untyped
        end
      end
    end
  end
end
