module Gitlab
  module Ci
    class Config
      module Entry
        #
        # Entry that represents the interruptible value.
        #
        class Timeout < ::Gitlab::Config::Entry::Node
          include ::Gitlab::Config::Entry::Validatable
        end
      end
    end
  end
end
