module ResourceEvents
  class MergeIntoNotesService
    @resource: untyped

    @current_user: untyped

    @params: untyped

    include Gitlab::Utils::StrongMemoize

    SYNTHETIC_NOTE_BUILDER_SERVICES: ::Array[untyped]

    attr_reader resource: untyped

    attr_reader current_user: untyped

    attr_reader params: untyped

    def initialize: (untyped resource, untyped current_user, ?::Hash[untyped, untyped] params) -> void

    def execute: (?untyped notes) -> untyped

    private

    def synthetic_notes: () -> untyped
  end
end
