# Deprecated:
#   All remaining references to this type always return nil.
#   Remove during any major release.
module Types
  module Metrics
    module Dashboards
      # rubocop:disable Graphql/AuthorizeTypes -- there is no object to authorize
      class AnnotationType < ::Types::BaseObject
      end
    end
  end
end
