module API
  module Helpers
    module Authz
      module PostfilteringHelpers
        def filter_with_logging: (collection: untyped, filter_proc: untyped, resource_type: untyped) -> untyped
      end
    end
  end
end
