module Gitlab
  module Diff
    module Formatters
      class ImageFormatter < BaseFormatter
        @x: untyped

        @y: untyped

        @width: untyped

        @height: untyped

        @ignore_whitespace_change: untyped

        @key: untyped

        attr_reader width: untyped

        attr_reader height: untyped

        attr_reader x: untyped

        attr_reader y: untyped

        def initialize: (untyped attrs) -> void

        def key: () -> untyped

        def complete?: () -> untyped

        def to_h: () -> untyped

        def position_type: () -> "image"

        def ==: (untyped other) -> untyped
      end
    end
  end
end
