module Gitlab
  module Diff
    module Formatters
      class TextFormatter < BaseFormatter
        @old_line: untyped

        @new_line: untyped

        @line_range: untyped

        @ignore_whitespace_change: untyped

        @key: untyped

        attr_reader old_line: untyped

        attr_reader new_line: untyped

        attr_reader line_range: untyped

        def initialize: (untyped attrs) -> void

        def key: () -> untyped

        def complete?: () -> untyped

        def to_h: () -> untyped

        def line_age: () -> (nil | "new" | "old")

        def position_type: () -> "text"

        def ==: (untyped other) -> untyped
      end
    end
  end
end
