module Users
  class RespondToTermsService
    @user: untyped

    @term: untyped

    def initialize: (untyped user, untyped term) -> void

    # rubocop: disable CodeReuse/ActiveRecord
    def execute: (accepted: untyped) -> untyped

    private

    def store_accepted_term: (untyped accepted) -> untyped
  end
end
