module Users
  class UpdateHighestMemberRoleService < BaseService
    @user: untyped

    @user_highest_role: untyped

    @highest_access_level: untyped

    attr_reader user: untyped

    def initialize: (untyped user) -> void

    def execute: () -> (true | untyped)

    private

    def user_highest_role: () -> untyped

    def highest_access_level: () -> untyped
  end
end
