module Users
  class UpsertCreditCardValidationService < BaseService
    @params: untyped

    attr_reader params: untyped

    def initialize: (untyped params) -> void

    def execute: () -> untyped

    private

    def user_id: () -> untyped

    def credit_card_validated_at: () -> untyped

    def last_digits: () -> untyped

    def holder_name: () -> untyped

    def network: () -> untyped

    def zuora_payment_method_xid: () -> untyped

    def stripe_setup_intent_xid: () -> untyped

    def stripe_payment_method_xid: () -> untyped

    def stripe_card_fingerprint: () -> untyped

    def expiration_date: () -> untyped

    def success: () -> untyped

    def error: () -> untyped

    def blocked: () -> untyped
  end
end
