module Projects
  module Settings
    class PackagesAndRegistriesController < Projects::ApplicationController
      @hide_search_settings: untyped

      def show: () -> nil

      def cleanup_tags: () -> untyped

      private

      def packages_and_registries_settings_enabled!: () -> (untyped | nil)

      def registry_settings_enabled!: () -> (untyped | nil)

      def set_feature_flag_packages_protected_packages: () -> untyped

      def set_feature_flag_container_registry_protected_containers_delete: () -> untyped
    end
  end
end
