module Projects
  module ErrorTracking
    class StackTracesController < Projects::ErrorTracking::BaseController
      def index: () -> untyped

      private

      def fetch_latest_event_issue: () -> untyped

      def serialize_error_event: (untyped event) -> untyped
    end
  end
end
