module SystemCheck
  module RakeTask
    # Used by gitlab:gitaly:check rake task
    class GitalyTask
      extend RakeTaskHelpers

      def self.name: () -> "Gitaly"

      def self.checks: () -> ::Array[untyped]
    end
  end
end
