module SystemCheck
  module RakeTask
    # Provides the run! method intended to be called from system check rake tasks
    module RakeTaskHelpers
      include ::SystemCheck::Helpers

      def run!: () -> untyped

      def run_checks!: () -> untyped

      def name: () -> untyped

      def checks: () -> untyped
    end
  end
end
