module Clusters
  module Agents
    class CreateActivityEventService
      @agent: untyped

      @params: untyped

      def initialize: (untyped agent, **untyped params) -> void

      def execute: () -> untyped

      private

      attr_reader agent: untyped

      attr_reader params: untyped

      def schedule_cleanup_at: () -> untyped
    end
  end
end
