module Clusters
  module Agents
    class CreateService < BaseService
      def execute: () -> untyped

      private

      def cluster_agent_permissions?: () -> untyped

      def error_no_permissions: () -> untyped
    end
  end
end
