module Gitlab
  module Ci
    module Reports
      module Security
        class Analyzer
          @id: untyped

          @name: untyped

          @version: untyped

          @vendor: untyped

          attr_reader id: untyped

          attr_reader name: untyped

          attr_reader version: untyped

          attr_reader vendor: untyped

          def initialize: (id: untyped, name: untyped, version: untyped, vendor: untyped) -> void
        end
      end
    end
  end
end
