module Uploads
  class DestroyService < BaseService
    @model: untyped

    @current_user: untyped

    attr_accessor model: untyped

    attr_accessor current_user: untyped

    def initialize: (untyped model, ?untyped? user) -> void

    def execute: (untyped upload) -> untyped
  end
end
