module Gitlab
  module Utils
    module DelegatorOverride
      class Error
        @method_name: untyped

        @target_class: untyped

        @target_location: untyped

        @delegator_class: untyped

        @delegator_location: untyped

        attr_accessor method_name: untyped

        attr_accessor target_class: untyped

        attr_accessor target_location: untyped

        attr_accessor delegator_class: untyped

        attr_accessor delegator_location: untyped

        def initialize: (untyped method_name, untyped target_class, untyped target_location, untyped delegator_class, untyped delegator_location) -> void

        def to_s: () -> ::String
      end
    end
  end
end
