module Bitbucket
  module Representation
    class Comment < Representation::Base
      def author: () -> untyped

      def author_nickname: () -> untyped

      def note: () -> untyped

      def created_at: () -> untyped

      def updated_at: () -> untyped

      private

      def user: () -> untyped
    end
  end
end
