module Bitbucket
  module Representation
    class PullRequestComment < Comment
      def iid: () -> untyped

      def file_path: () -> untyped

      def old_pos: () -> untyped

      def new_pos: () -> untyped

      def parent_id: () -> untyped

      def inline?: () -> untyped

      def has_parent?: () -> untyped

      def deleted?: () -> untyped

      private

      def inline: () -> untyped
    end
  end
end
