module Gitlab
  module Audit
    class Target
      @object: untyped

      def initialize: (untyped object) -> void

      def type: () -> untyped

      def details: () -> untyped
    end
  end
end
