module WorkItems
  module Widgets
    class TimeTracking < Base
      def self.quick_action_commands: () -> ::Array[:estimate | :estimate_time | :remove_estimate | :remove_time_estimate | :spend | :spent | :spend_time | :remove_time_spent]

      def self.quick_action_params: () -> ::Array[:time_estimate | :spend_time]
    end
  end
end
