module Clusters
  module Agents
    class DashboardController < ApplicationController
      @agent: untyped

      include KasCookie

      def index: () -> nil

      def show: () -> nil

      private

      def find_agent: () -> untyped

      def check_feature_flag!: () -> (untyped | nil)

      def authorize_read_cluster_agent!: () -> (untyped | nil)
    end
  end
end
