module DeployTokenMethods
  def create_deploy_token_for: (untyped entity, untyped current_user, untyped params) -> untyped

  def destroy_deploy_token: (untyped entity, untyped params) -> untyped

  def create_deploy_token_payload_for: (untyped deploy_token) -> untyped
end
