module ValidatesClassificationLabel
  def validate_classification_label_param!: (untyped record, untyped attribute_name) -> (nil | untyped)

  def rejection_reason_for_label: (untyped label) -> untyped

  def classification_label_change?: (untyped record, untyped attribute_name) -> untyped
end
