module Sidebars
  module Admin
    module Menus
      class MessagesMenu < ::Sidebars::Admin::BaseMenu
        def link: () -> untyped

        def title: () -> untyped

        def sprite_icon: () -> "bullhorn"

        def active_routes: () -> { controller: :broadcast_messages }
      end
    end
  end
end
