module Gitlab
  module Terraform
    class StateMigrationHelper
      def self.migrate_to_remote_storage: () { (?) -> untyped } -> untyped

      private

      def self.batch_size: () -> untyped

      def self.migrate_in_batches: (untyped versions, untyped store) { (untyped) -> untyped } -> untyped
    end
  end
end
