# Class for retrieving information about emoji awarded _by_ a particular user.
module AwardEmojis
  class CollectUserEmojiService
    @current_user: untyped

    attr_reader current_user: untyped

    # current_user - The User to generate the data for.
    def initialize: (?untyped? current_user) -> void

    def execute: () -> (::Array[untyped] | untyped)
  end
end
