module Types
  class WorkItemType < BaseObject
    include ::IssuablesHelper

    def self.authorization_scopes: () -> untyped

    def work_item_type: () -> untyped

    def comment_templates_paths: () -> untyped

    def create_note_email: () -> untyped

    def archived: () -> untyped

    def show_plan_upgrade_promotion: () -> untyped
  end
end
