module Gitlab
  module Git
    class RefResolver
      @repository: untyped

      @origin_ref: untyped

      @ref_name: untyped

      include Gitlab::Utils::StrongMemoize

      def initialize: (untyped repository, untyped origin_ref) -> void

      def resolved_ref: () -> (untyped | nil | nil | untyped | untyped | nil)

      def ambiguous?: () -> untyped

      def branch?: () -> untyped

      def tag?: () -> untyped

      def merge_request?: () -> untyped

      def workload?: () -> untyped

      private

      def full_branch_or_tag_path?: () -> untyped

      def merge_request_or_workload_path?: () -> untyped

      def branch_exists?: () -> untyped

      def tag_exists?: () -> untyped
    end
  end
end
