module Gitlab
  module Git
    class WikiFile
      @mime_type: untyped

      @raw_data: untyped

      @name: untyped

      @path: untyped

      attr_reader mime_type: untyped

      attr_reader raw_data: untyped

      attr_reader name: untyped

      attr_reader path: untyped

      def initialize: (untyped blob) -> void
    end
  end
end
