module Gitlab
  module Git
    class WikiPage
      @url_path: untyped

      @title: untyped

      @format: untyped

      @path: untyped

      @raw_data: untyped

      @name: untyped

      @historical: untyped

      @version: untyped

      @text_data: untyped

      attr_reader url_path: untyped

      attr_reader title: untyped

      attr_reader format: untyped

      attr_reader path: untyped

      attr_reader version: untyped

      attr_reader raw_data: untyped

      attr_reader name: untyped

      attr_reader historical: untyped

      attr_reader formatted_data: untyped

      def initialize: (untyped hash) -> void

      def historical?: () -> untyped

      def text_data: () -> untyped

      def raw_data=: (untyped data) -> untyped
    end
  end
end
