module Resolvers
  module Environments
    class LastDeploymentResolver < BaseResolver
      def resolve: (status: untyped) -> (nil | untyped)

      private

      def find_last_deployment: (untyped status) -> untyped

      def validate!: (untyped status) -> (untyped | nil)
    end
  end
end
