module CustomerRelations
  module Organizations
    class BaseService < ::BaseGroupService
      private

      def allowed?: () -> untyped

      def error: (untyped message) -> untyped
    end
  end
end
