module Gitlab
  module Jira
    module Dvcs
      ENCODED_SLASH: "@"

      SLASH: "/"

      ENCODED_ROUTE_REGEX: ::Regexp

      def self.encode_slash: (untyped path) -> untyped

      def self.decode_slash: (untyped path) -> untyped

      # To present two types of projects stored by Jira,
      # Type 1 are projects imported prior to nested group support,
      # those project names are not full_path, so they are presented differently
      # to maintain backwards compatibility.
      # Type 2 are projects imported after nested group support,
      # those project names are encoded full path
      #
      # @param [Project] project
      def self.encode_project_name: (untyped project) -> untyped

      # To interpret two types of project names stored by Jira (see `encode_project_name`)
      #
      # @param [String] project
      #  Either an encoded full path, or just project name
      # @param [String] namespace
      def self.restore_full_path: (namespace: untyped, project: untyped) -> (untyped | ::String)
    end
  end
end
