module Gitlab
  module Schema
    module Validation
      module Sources
        module ConnectionAdapters
          class PgAdapter < Base
            @connection: untyped

            def initialize: (untyped connection) -> void

            def current_schema: () -> untyped

            def exec_query: (untyped sql, untyped schemas) -> untyped

            def select_rows: (untyped sql, untyped schemas) -> untyped
          end
        end
      end
    end
  end
end
