module Gitlab
  module SidekiqMiddleware
    module Identity
      class Restore
        include Sidekiq::ServerMiddleware

        def call: (untyped _worker, untyped job, untyped _queue) { () -> untyped } -> untyped
      end
    end
  end
end
