module Gitlab
  module Ci
    module Pipeline
      module Expression
        module Lexeme
          class And < Lexeme::LogicalOperator
            PATTERN: ::Regexp

            def evaluate: (?::Hash[untyped, untyped] variables) -> untyped

            def self.build: (untyped _value, untyped behind, untyped ahead) -> untyped

            def self.precedence: () -> 11
          end
        end
      end
    end
  end
end
