module Gitlab
  module Ci
    module Pipeline
      module Expression
        module Lexeme
          class Null < Lexeme::Value
            PATTERN: ::Regexp

            def initialize: (?untyped? value) -> void

            def evaluate: (?::Hash[untyped, untyped] variables) -> nil

            def inspect: () -> "null"

            def self.build: (untyped _value) -> untyped
          end
        end
      end
    end
  end
end
