module ActivityPub
  module Projects
    class ApplicationController < ::ActivityPub::ApplicationController
      @project: untyped

      private

      def project: () -> (nil | untyped)

      def auth_proc: () -> untyped

      def ensure_project_feature_flag: () -> (untyped | nil)

      def permitted_params: () -> untyped
    end
  end
end
