module ActivityPub
  module Projects
    class ReleasesController < ApplicationController
      @payload: untyped

      def index: () -> untyped

      def inbox: () -> untyped

      def outbox: () -> untyped

      private

      def releases: (?::Hash[untyped, untyped] params) -> untyped

      def enforce_payload: () -> (nil | false)

      def payload: () -> untyped

      def follow?: () -> untyped

      def unfollow?: () -> untyped

      def inbox_service: () -> (untyped | nil)
    end
  end
end
