module ObjectPool
  class JoinWorker
    include ApplicationWorker

    include ObjectPoolQueue

    # The use of pool id is deprecated. Keeping the argument allows old jobs to
    # still be performed.
    def perform: (untyped _pool_id, untyped project_id) -> (nil | untyped)
  end
end
