module API
  module Entities
    module WorkItems
      module Features
        module CommonExposures
          extend ActiveSupport::Concern

          include ConditionalExposureHelpers
        end
      end
    end
  end
end
