module API
  module Entities
    module WorkItems
      module Features
        class Designs < Grape::Entity
          class DesignCollection < Grape::Entity
          end
        end
      end
    end
  end
end
