module Admin
  module ApplicationSettings
    class ServiceAccountsController < Admin::ApplicationController
      private

      def authorize_admin_service_accounts!: () -> (untyped | nil)
    end
  end
end
