module Ml
  class FindModelService
    @project: untyped

    @name: untyped

    @model_id: untyped

    def initialize: (untyped project, ?untyped? name, ?untyped? model_id) -> void

    def execute: () -> (untyped | nil)

    def find_by_model_id: () -> untyped

    def find_by_project_and_name: () -> untyped
  end
end
