module Sidebars
  module Projects
    module SuperSidebarMenus
      class AnalyzeMenu < ::Sidebars::Menu
        def title: () -> untyped

        def sprite_icon: () -> "chart"

        def configure_menu_items: () -> untyped
      end
    end
  end
end
