module Resolvers
  module ErrorTracking
    class SentryDetailedErrorResolver < BaseResolver
      def resolve: (id: untyped) -> untyped

      private

      def project: () -> untyped
    end
  end
end
