module Types
  module CustomerRelations
    class ContactStateCountsType < Types::BaseObject
      self.@available_contact_states: untyped

      def self.available_contact_states: () -> untyped
    end
  end
end
