class Projects::MergeRequests::ContentController < Projects::MergeRequests::ApplicationController
  FAST_POLLING_INTERVAL: untyped

  SLOW_POLLING_INTERVAL: untyped

  def widget: () -> untyped

  def cached_widget: () -> untyped

  private

  def set_polling_header: () -> untyped

  def serializer: (untyped entity) -> untyped
end
