module Resolvers
  module Analytics
    module CycleAnalytics
      module ValueStreams
        class StageMetricsResolver < BaseResolver
          def resolve: (**untyped args) -> untyped

          private

          def transform_params: (untyped args, untyped _stage) -> untyped
        end
      end
    end
  end
end
