module Resolvers
  module Analytics
    module CycleAnalytics
      module ValueStreams
        class StageItemsResolver < BaseResolver
          def resolve: (?sort: ::Hash[untyped, untyped]) -> untyped
        end
      end
    end
  end
end
