module ClickHouse
  module SchemaMigrations
    def self.touch_all: (untyped connection, untyped database) -> untyped

    def self.load_all: (untyped connection, untyped database) -> untyped
  end
end
