module ClickHouse
  module WriteBuffer
    extend Gitlab::Redis::BackwardsCompatibility

    BUFFER_KEY_PREFIX: "clickhouse_write_buffer_"

    def self.add: (untyped table_name, untyped event_hash) -> untyped

    def self.pop: (untyped table_name, untyped limit) -> untyped

    private

    def self.buffer_key: (untyped table_name) -> ::String
  end
end
