module SystemCheck
  module App
    class LogWritableCheck < SystemCheck::BaseCheck
      def check?: () -> untyped

      def show_error: () -> untyped

      private

      def log_path: () -> untyped
    end
  end
end
