module SystemCheck
  module App
    class ProjectsHaveNamespaceCheck < SystemCheck::BaseCheck
      def skip?: () -> untyped

      def multi_check: () -> untyped

      def show_error: () -> untyped
    end
  end
end
