module Gitlab
  module Kubernetes
    class GenericSecret
      @name: untyped

      @data: untyped

      @namespace_name: untyped

      attr_reader name: untyped

      attr_reader data: untyped

      attr_reader namespace_name: untyped

      def initialize: (untyped name, untyped data, untyped namespace_name) -> void

      def generate: () -> untyped

      private

      def generic_secret_type: () -> "Opaque"

      def metadata: () -> { name: untyped, namespace: untyped }
    end
  end
end
