module Gitlab
  module Kubernetes
    class TlsSecret
      @name: untyped

      @cert: untyped

      @key: untyped

      @namespace_name: untyped

      attr_reader name: untyped

      attr_reader cert: untyped

      attr_reader key: untyped

      attr_reader namespace_name: untyped

      def initialize: (untyped name, untyped cert, untyped key, untyped namespace_name) -> void

      def generate: () -> untyped

      private

      def tls_secret_type: () -> "kubernetes.io/tls"

      def metadata: () -> { name: untyped, namespace: untyped }

      def data: () -> { :"tls.crt" => untyped, :"tls.key" => untyped }
    end
  end
end
