module Ci
  class FreezePeriodsFinder
    @project: untyped

    @current_user: untyped

    def initialize: (untyped project, ?untyped? current_user) -> void

    def execute: () -> untyped
  end
end
