module Ci
  class JobArtifactsFinder
    @project: untyped

    @params: untyped

    def initialize: (untyped project, ?::Hash[untyped, untyped] params) -> void

    def execute: () -> untyped

    private

    def sort_key: () -> untyped

    def sort: (untyped artifacts) -> untyped
  end
end
