module BulkImports
  module Groups
    module Pipelines
      class SubgroupEntitiesPipeline
        include Pipeline

        include HexdigestCacheStrategy

        def load: (untyped context, untyped data) -> untyped
      end
    end
  end
end
