module Gitlab
  module Database
    module LoadBalancing
      # Hostnames returned in SRV records cannot sometimes be resolved by a local
      # resolver, however, there's a possibility that their A/AAAA records are
      # returned as part of the SRV query in the additional section, so we try
      # to extract the IPs from there first, failing back to querying the
      # hostnames A/AAAA records one by one, using the same resolver that
      # queried the SRV record.
      class SrvResolver
        @resolver: untyped

        @additional: untyped

        include Gitlab::Utils::StrongMemoize

        attr_reader resolver: untyped

        attr_reader additional: untyped

        def initialize: (untyped resolver, untyped additional) -> void

        def address_for: (untyped host) -> untyped

        private

        def addresses_from_additional: () -> untyped

        def resolve_host: (untyped host) -> untyped
      end
    end
  end
end
