module Namespaces
  module ServiceAccounts
    class BaseDeleteService < BaseService
      @current_user: untyped

      @user: untyped

      attr_accessor current_user: untyped

      attr_accessor user: untyped

      def initialize: (untyped current_user, untyped user) -> void

      def execute: (?::Hash[untyped, untyped] options) -> untyped

      private

      def can_delete_service_account?: () -> (false | untyped)

      def user_provisioned_resource: () -> untyped

      def delete_user: (untyped options) -> untyped

      def error_messages: () -> { no_permission: untyped }

      def error: (untyped message, untyped reason) -> untyped

      def success: () -> untyped
    end
  end
end
