module Types
  module WorkItems
    class TypeType < BaseObject
      def self.authorization_scopes: () -> untyped

      def widgets: () -> untyped

      def widget_definitions: () -> untyped

      def supported_conversion_types: () -> untyped

      def unavailable_widgets_on_conversion: (target: untyped) -> (::Array[untyped] | untyped)
    end
  end
end
