module Types
  module WorkItems
    module WidgetInterface
      include ::Types::BaseInterface

      # Whenever a new widget is added make sure to update the spec to avoid N + 1 queries in
      # spec/requests/api/graphql/project/work_items_spec.rb and add the necessary preloads
      # in app/graphql/resolvers/work_items_resolver.rb
      TYPE_MAPPINGS: ::Hash[untyped, untyped]

      def self.type_mappings: () -> untyped

      def self.resolve_type: (untyped object, untyped context) -> untyped
    end
  end
end
