module SystemCheck
  # Used by gitlab:gitlab_shell:check rake task
  class GitlabShellCheck < BaseCheck
    def multi_check: () -> untyped

    private

    def check_gitlab_shell: () -> untyped

    def check_gitlab_shell_self_test: () -> untyped

    def gitlab_shell_path: () -> untyped

    def gitlab_shell_version: () -> untyped
  end
end
