module Projects
  module Import
    class JiraController < Projects::ApplicationController
      def show: () -> nil

      private

      def validate_jira_import_settings!: () -> untyped

      def jira_integration: () -> untyped

      def jira_import_params: () -> untyped
    end
  end
end
