module Spam
  class AkismetMarkAsSpamService
    @target: untyped

    @options: untyped

    include ::AkismetMethods

    attr_accessor target: untyped

    attr_accessor options: untyped

    def initialize: (target: untyped) -> void

    def execute: () -> (nil | untyped)
  end
end
