module Gitlab
  module SlashCommands
    module Presenters
      module IncidentManagement
        class IncidentNew < Presenters::Base
          def present: (untyped message) -> untyped
        end
      end
    end
  end
end
