module Gitlab
  module Backup
    # GitLab Backup CLI
    module Cli
      Error: untyped

      # Entrypoint for the application
      # Run any initialization logic from here
      def self.start: (untyped argv) -> untyped

      def self.update_process_title!: (?untyped? status_message) -> untyped

      def self.root: () -> untyped
    end
  end
end
