module Ci
  class PipelineCreatedEvent < ::Gitlab::EventStore::Event
    def schema: () -> { "type" => "object", "required" => ::Array["pipeline_id" | "partition_id"], "properties" => { "pipeline_id" => { "type" => "integer" }, "partition_id" => { "type" => "integer" } } }
  end
end
