module Gitlab
  module UrlBlockers
    class IpAllowlistEntry
      @ip: untyped

      @port: untyped

      attr_reader ip: untyped

      attr_reader port: untyped

      # Argument ip should be an IPAddr object
      def initialize: (untyped ip, ?port: untyped?) -> void

      def match?: (untyped requested_ip, ?untyped? requested_port) -> (false | true | untyped)

      private

      # Prior to ipaddr v1.2.3, if the allow list were the IPv4 to IPv6
      # mapped address ::ffff:169.254.168.100 and the requested IP were
      # 169.254.168.100 or ::ffff:169.254.168.100, the IP would be
      # considered in the allow list. However, with
      # https://github.com/ruby/ipaddr/pull/31, IPAddr#include? will
      # only match if the IP versions are the same. This method
      # preserves backwards compatibility if the versions differ by
      # checking inclusion by coercing an IPv4 address to its IPv6
      # mapped address.
      def ip_include?: (untyped requested_ip) -> (true | untyped | false)
    end
  end
end
