module ErrorTrackingOpenAPI
  # Customize default settings for the SDK using block.
  #   ErrorTrackingOpenAPI.configure do |config|
  #     config.username = "xxx"
  #     config.password = "xxx"
  #   end
  # If no block given, return the default Configuration object.
  def self.configure: () ?{ (untyped) -> untyped } -> untyped
end
