module Gitlab
  module Ci
    module Parsers
      module Instrumentation
        BUCKETS: ::Array[::Float | 1 | 5 | 10]

        def parse!: (*untyped, **untyped) ?{ (?) -> untyped } -> untyped
      end
    end
  end
end
