module API
  module Entities
    module Ml
      module Mlflow
        class GetDownload < Grape::Entity
          private

          def artifact_uri: () -> ::String
        end
      end
    end
  end
end
