module CustomerRelations
  module Contacts
    class CreateService < BaseService
      def execute: () -> untyped

      private

      def error_creating: (untyped contact) -> untyped
    end
  end
end
