module Gitlab
  module Graphql
    module Loaders
      class BatchProjectStatisticsLoader
        @project_id: untyped

        attr_reader project_id: untyped

        def initialize: (untyped project_id) -> void

        def find: () -> untyped
      end
    end
  end
end
