module Ci
  class VariableValue
    @variable: untyped

    def initialize: (untyped variable) -> void

    def evaluate: () -> (nil | untyped)

    private

    attr_reader variable: untyped
  end
end
