module Emails
  module Releases
    @release: untyped

    @project: untyped

    @target_url: untyped

    @recipient: untyped

    def new_release_email: (untyped user_id, untyped release, ?untyped? reason) -> untyped

    private

    def release_email_subject: () -> ::String
  end
end
