module Emails
  module RemoteMirrors
    @remote_mirror: untyped

    @project: untyped

    @target_url: untyped

    def remote_mirror_update_failed_email: (untyped remote_mirror_id, untyped recipient_id) -> untyped
  end
end
