module MergeRequests
  module Mergeability
    class CheckRebaseStatusService < CheckBaseService
      def execute: () -> untyped

      def skip?: () -> untyped

      def cacheable?: () -> false
    end
  end
end
