module MergeRequests
  module Mergeability
    class CheckCommitsStatusService < CheckBaseService
      def execute: () -> untyped

      def skip?: () -> false

      def cacheable?: () -> false
    end
  end
end
