module ActivityPub
  # Serializer for the `Actor` ActivityStreams model.
  # Reference: https://www.w3.org/TR/activitystreams-core/#actors
  class ActorSerializer < ObjectSerializer
    MissingOutboxError: untyped

    def represent: (untyped resource, ?::Hash[untyped, untyped] opts, ?untyped? entity_class) -> untyped

    private

    def validate_response: (untyped response, untyped _opts) -> untyped

    def wrap: (untyped serialized, untyped opts) -> untyped
  end
end
