module Import
  class GithubFailureEntity < Grape::Entity
    private

    # rubocop:disable Metrics/CyclomaticComplexity
    def title: (untyped failure) -> untyped

    def build_url: (untyped failure) -> ("" | untyped)

    def host: (untyped uri) -> untyped

    def escape: (untyped str) -> untyped
  end
end
