module CustomerRelations
  class GroupMigrationService
    @old_group_id: untyped

    @new_group_id: untyped

    @was_crm_source: untyped

    def initialize: (untyped old_group_id, untyped new_group_id, untyped was_crm_source) -> void

    def execute: () -> (nil | untyped)

    private

    def execute_sql: (untyped sql, untyped args) -> untyped

    def copy_organizations: () -> untyped

    def copy_contacts: () -> untyped

    def update_issues: () -> untyped
  end
end
