module Gitlab
  module GrapeOpenapi
    module Models
      class Info
        @title: untyped

        @description: untyped

        @terms_of_service: untyped

        @version: untyped

        @license: untyped

        attr_accessor title: untyped

        attr_accessor description: untyped

        attr_accessor terms_of_service: untyped

        attr_accessor version: untyped

        attr_accessor license: untyped

        def initialize: (**untyped options) -> void

        def to_h: () -> untyped
      end
    end
  end
end
