module Gitlab
  module GrapeOpenapi
    module Models
      # https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#security-scheme-object
      class SecurityScheme
        @type: untyped

        @description: untyped

        @name: untyped

        @in: untyped

        @scheme: untyped

        @bearer_format: untyped

        @flows: untyped

        @open_id_connect_url: untyped

        VALID_TYPES: ::Array["apiKey" | "http" | "oauth2" | "openIdConnect"]

        VALID_IN_VALUES: ::Array["query" | "header" | "cookie"]

        VALID_HTTP_SCHEMES: ::Array["basic" | "bearer" | "oauth"]

        attr_accessor type: untyped

        attr_accessor description: untyped

        attr_accessor name: untyped

        attr_accessor in: untyped

        attr_accessor scheme: untyped

        attr_accessor bearer_format: untyped

        attr_accessor flows: untyped

        attr_accessor open_id_connect_url: untyped

        def initialize: (type: untyped, **untyped options) -> void

        def to_h: () -> untyped

        private

        def validate_type!: () -> (nil | untyped)

        def validate_in!: () -> (nil | untyped)

        def validate_http_scheme!: () -> (nil | untyped)

        def validate_oauth2_flows!: () -> untyped

        # rubocop:disable Metrics/CyclomaticComplexity -- Method is clear and readable
        def validate_flow_config!: (untyped flow_type, untyped config) -> untyped

        def flows_to_hash: (untyped flows) -> untyped
      end
    end
  end
end
