module Gitlab
  module GrapeOpenapi
    module Models
      class Tag
        @name: untyped

        def self.normalize_tag_name: (untyped tag_name) -> untyped

        def self.apply_overrides: (untyped text) -> untyped

        attr_reader name: untyped

        def initialize: (untyped name) -> void

        def to_h: () -> untyped

        def description: () -> ::String
      end
    end
  end
end
