module Gitlab
  module Schema
    module Validation
      module Validators
        class ExtraIndexes < Base
          ERROR_MESSAGE: "The index %s is present in the database, but not in the structure.sql file"

          def execute: () -> untyped
        end
      end
    end
  end
end
