class Dashboard::ApplicationController < ApplicationController
  @projects: untyped

  include ControllerWithCrossProjectAccessCheck

  include RecordUserLastActivity

  private

  def projects: () -> untyped
end
