module Repositories
  class BranchNamesFinder
    @repository: untyped

    @params: untyped

    attr_reader repository: untyped

    attr_reader params: untyped

    def initialize: (untyped repository, ?::Hash[untyped, untyped] params) -> void

    def execute: () -> (nil | untyped)

    private

    def search: () -> untyped

    def offset: () -> untyped

    def limit: () -> untyped
  end
end
