module Security
  module CiConfiguration
    class SecretDetectionCreateService < ::Security::CiConfiguration::BaseCreateService
      @params: untyped

      @commit_on_default: untyped

      @branch_name: untyped

      attr_reader params: untyped

      def initialize: (untyped project, untyped current_user, ?::Hash[untyped, untyped] params, ?commit_on_default: bool) -> void

      private

      def remove_branch_on_exception: () -> (untyped | nil)

      def action: () -> untyped

      def next_branch: () -> "set-secret-detection-config"

      def message: () -> untyped

      def description: () -> untyped

      def name: () -> "Secret Detection"
    end
  end
end
