module Gitlab
  module SidekiqMiddleware
    module DuplicateJobs
      class Server
        def call: (untyped worker, untyped job, untyped queue) { (?) -> untyped } -> untyped
      end
    end
  end
end
