module Ci
  # TODO: when using this class with exposed artifacts we see that there are
  # 2 responsibilities:
  # 1. reactive caching interface (same in all cases)
  # 2. data generator (report comparison in most of the case but not always)
  # issue: https://gitlab.com/gitlab-org/gitlab/issues/34224
  class CompareReportsBaseService < ::BaseService
    def execute: (untyped base_pipeline, untyped head_pipeline) -> untyped

    def latest?: (untyped base_pipeline, untyped head_pipeline, untyped data) -> untyped

    def parsing_payload: (untyped base_pipeline, untyped head_pipeline) -> { status: :parsing, key: untyped }

    def build_comparer: (untyped base_report, untyped head_report) -> untyped

    private

    def key: (untyped base_pipeline, untyped head_pipeline) -> ::Array[untyped]

    def comparer_class: () -> untyped

    def serializer_class: () -> untyped

    def serializer_params: () -> { project: untyped, current_user: untyped }

    def get_report: (untyped pipeline) -> untyped
  end
end
