module Ci
  class ProcessPipelineService
    @pipeline: untyped

    @metrics: untyped

    attr_reader pipeline: untyped

    def initialize: (untyped pipeline) -> void

    def execute: () -> untyped

    def metrics: () -> untyped

    private

    def increment_processing_counter: () -> untyped
  end
end
