module API
  module Helpers
    module BulkImports
      module AuditHelpers
        def log_direct_transfer_audit_event: (untyped event_name, untyped event_message, untyped current_user, untyped scope) -> untyped
      end
    end
  end
end
