module Gitlab
  module View
    module Presenter
      class Factory
        @subject: untyped

        @attributes: untyped

        def initialize: (untyped subject, **untyped attributes) -> void

        def fabricate!: () -> untyped

        private

        attr_reader subject: untyped

        attr_reader attributes: untyped

        def presenter_class: () -> untyped
      end
    end
  end
end
