module Ci
  module HidableVariable
    extend ActiveSupport::Concern

    private

    def validate_masked_and_hidden_on_create: () -> (nil | untyped)

    def validate_masked_and_hidden_on_update: () -> (nil | untyped)
  end
end
