module Backup
  module Tasks
    class Pages < Task
      @target: untyped

      # pages used to deploy tmp files to this path
      # if some of these files are still there, we don't need them in the backup
      LEGACY_PAGES_TMP_PATH: "@pages.tmp"

      def self.id: () -> "pages"

      def human_name: () -> untyped

      def destination_path: () -> "pages.tar.gz"

      private

      def target: () -> untyped

      def storage_path: () -> untyped
    end
  end
end
