module BulkImports
  module Projects
    module Pipelines
      class RepositoryBundlePipeline
        @tmpdir: untyped

        include Pipeline

        include IndexCacheStrategy

        def extract: (untyped _context) -> untyped

        def load: (untyped _context, untyped bundle_path) -> (nil | untyped)

        def after_run: (untyped _) -> untyped

        private

        def tar_filename: () -> ::String

        def targz_filename: () -> ::String

        def download_service: () -> untyped

        def decompression_service: () -> untyped

        def extraction_service: () -> untyped

        def tmpdir: () -> untyped
      end
    end
  end
end
