module Gitlab
  module Backup
    module Cli
      class GitlabConfig
        @source: untyped

        @config: untyped

        extend Forwardable

        def initialize: (untyped source) -> void

        def loaded?: () -> untyped

        private

        def load!: () -> untyped
      end
    end
  end
end
