module Gitlab
  module Backup
    module Cli
      module Tasks
        TASKS: ::Hash[untyped, untyped]

        def self.all: () -> untyped

        def self.build_each: (**untyped init_args) ?{ (untyped) -> untyped } -> untyped
      end
    end
  end
end
