module Gitlab
  module SidekiqMiddleware
    module AdminMode
      class Server
        def call: (untyped _worker, untyped job, untyped _queue) { () -> untyped } -> untyped
      end
    end
  end
end
