module Gitlab
  module Database
    class ConnectionTimer
      self.@interval: untyped

      @interval: untyped

      @starting_clock_value: untyped

      DEFAULT_INTERVAL: 3600

      RANDOMIZATION_INTERVAL: 600

      def self.configure: () { (untyped) -> untyped } -> untyped

      def self.starting_now: () -> untyped

      attr_writer self.interval: untyped

      def self.interval: () -> untyped

      def self.interval_with_randomization: () -> (untyped | nil)

      def self.current_clock_value: () -> untyped

      attr_reader interval: untyped

      attr_reader starting_clock_value: untyped

      def initialize: (untyped interval, untyped starting_clock_value) -> void

      def expired?: () -> untyped

      def reset!: () -> untyped
    end
  end
end
