module Gitlab
  module Database
    # Use this model with care: Retrieving bloat statistics
    # for all indexes can be expensive in a large database.
    #
    # Best used on a per-index basis.
    class PostgresIndexBloatEstimate < SharedModel
    end
  end
end
