module Gitlab
  module Database
    # This class provides a way to automatically execute code that relies on acquiring a database lock in a way
    # designed to minimize impact on a busy production database.
    #
    # A default timing configuration is provided that makes repeated attempts to acquire the necessary lock, with
    # varying lock_timeout settings, and also serves to limit the maximum number of attempts.
    class WithLockRetries
      @logger: untyped

      @klass: untyped

      @allow_savepoints: untyped

      @timing_configuration: untyped

      @env: untyped

      @current_iteration: untyped

      @log_params: untyped

      @connection: untyped

      @block: untyped

      AttemptsExhaustedError: untyped

      NULL_LOGGER: untyped

      # Each element of the array represents a retry iteration.
      # - DEFAULT_TIMING_CONFIGURATION.size provides the iteration count.
      # - First element: DB lock_timeout
      # - Second element: Sleep time after unsuccessful lock attempt (LockWaitTimeout error raised)
      # - Worst case, this configuration would retry for about 40 minutes.
      DEFAULT_TIMING_CONFIGURATION: untyped

      def initialize: (connection: untyped, ?logger: untyped, ?allow_savepoints: bool, ?timing_configuration: untyped, ?klass: untyped?, ?env: untyped) -> void

      # Executes a block of code, retrying it whenever a database lock can't be acquired in time
      #
      # When a database lock can't be acquired, ActiveRecord throws ActiveRecord::LockWaitTimeout
      # exception which we intercept to re-execute the block of code, until it finishes or we reach the
      # max attempt limit. The default behavior when max attempts have been reached is to make a final attempt with the
      # lock_timeout disabled, but this can be altered with the raise_on_exhaustion parameter.
      #
      # @see DEFAULT_TIMING_CONFIGURATION for the timings used when attempting a retry
      # @param [Boolean] raise_on_exhaustion whether to raise `AttemptsExhaustedError` when exhausting max attempts
      # @param [Proc] block of code that will be executed
      def run: (?raise_on_exhaustion: bool) ?{ (?) -> untyped } -> untyped

      private

      attr_reader logger: untyped

      attr_reader env: untyped

      attr_reader block: untyped

      attr_reader current_iteration: untyped

      attr_reader log_params: untyped

      attr_reader timing_configuration: untyped

      attr_reader connection: untyped

      def run_block: () -> untyped

      def run_block_with_lock_timeout: () -> untyped

      def retry_with_lock_timeout?: () -> untyped

      def wait_until_next_retry: () -> untyped

      def run_block_without_lock_timeout: () -> untyped

      def lock_retries_disabled?: () -> untyped

      def log: (untyped params) -> untyped

      def execute: (untyped statement) -> untyped

      def retry_count: () -> untyped

      def current_lock_timeout_in_ms: () -> untyped

      def current_sleep_time_in_seconds: () -> untyped

      def disable_idle_in_transaction_timeout: () -> untyped

      def disable_lock_timeout: () -> untyped

      def reset_db_settings: () -> untyped
    end
  end
end
