module Projects
  class DailyStatisticsFinder
    @project: untyped

    attr_reader project: untyped

    def initialize: (untyped project) -> void

    def fetches: () -> untyped

    def total_fetch_count: () -> untyped
  end
end
