module Pages
  module Domains
    class CreateService < BaseService
      def execute: () -> (nil | untyped)

      private

      def authorized?: () -> untyped

      def find_existing_domain: () -> untyped

      def publish_event: (untyped domain) -> untyped
    end
  end
end
