module Gitlab
  module Analytics
    module CycleAnalytics
      class BaseQueryBuilder
        @stage: untyped

        @params: untyped

        include Gitlab::CycleAnalytics::MetricsTables

        include StageQueryHelpers

        FINDER_CLASSES: ::Hash[untyped, untyped]

        DEFAULT_END_EVENT_FILTER: :finished

        def initialize: (stage: untyped, ?params: ::Hash[untyped, untyped]) -> void

        def build: () -> untyped

        private

        attr_reader stage: untyped

        attr_reader params: untyped

        def duration_condition: () -> untyped

        def finder: () -> untyped

        def parent_class: () -> untyped

        def build_finder_params: (untyped params) -> untyped

        def add_parent_model_params!: (untyped finder_params) -> untyped

        def add_time_range_params!: (untyped finder_params, untyped from, untyped to) -> untyped

        # rubocop: disable CodeReuse/ActiveRecord
        def apply_end_event_query_customization: (untyped query) -> untyped
      end
    end
  end
end
