class ContainerTagsSerializer < BaseSerializer
  def with_pagination: (untyped request, untyped response) -> untyped

  def paginated?: () -> untyped

  def represent: (untyped resource, ?::Hash[untyped, untyped] opts) -> untyped
end
