class DiffsMetadataEntity < DiffsEntity
  @presenters: untyped

  private

  def project_path: () -> untyped

  def project_name: () -> untyped

  def username: () -> untyped

  def user_full_name: () -> untyped

  def presenter: (untyped merge_request) -> untyped
end
