class IssueSerializer < BaseSerializer
  # This overrided method takes care of which entity should be used
  # to serialize the `issue` based on `serializer` key in `opts` param.
  # Hence, `entity` doesn't need to be declared on the class scope.
  def represent: (untyped issue, ?::Hash[untyped, untyped] opts) -> untyped

  def choose_entity: (untyped opts) -> untyped
end
