module Gitlab
  module Database
    module Migrations
      module Observers
        class MigrationObserver
          @connection: untyped

          @observation: untyped

          @output_dir: untyped

          attr_reader connection: untyped

          attr_reader observation: untyped

          attr_reader output_dir: untyped

          def initialize: (untyped observation, untyped output_dir, untyped connection) -> void

          def before: () -> nil

          def after: () -> nil

          def record: () -> untyped
        end
      end
    end
  end
end
