module Onboarding
  class ActionCardComponent < Onboarding::Component
    @title: untyped

    @description: untyped

    @icon: untyped

    @href: untyped

    @html_options: untyped

    @link_options: untyped

    VARIANT_OPTIONS: ::Array[:default | :success | :promo]

    def initialize: (?title: untyped?, ?description: untyped?, ?icon: untyped?, ?href: untyped?, ?link_options: ::Hash[untyped, untyped], **untyped html_options) -> void

    private

    def card_classes: () -> ::Array["action-card"]

    def card_icon: () -> untyped

    def link?: () -> untyped

    def html_options: () -> untyped
  end
end
