module Projects
  module Alerting
    class NotificationsController < Projects::ApplicationController
      @project: untyped

      @notification_payload: untyped

      include ActionController::HttpAuthentication::Basic

      include IncidentManagementFeatureFlag

      def create: () -> untyped

      private

      def project_without_auth: () -> untyped

      def extract_alert_manager_token: (untyped request) -> untyped

      def extract_bearer_token: (untyped request) -> untyped

      def extract_basic_auth_token: (untyped request) -> untyped

      def notify_service: () -> untyped

      def notify_service_class: () -> untyped

      def integration: () -> untyped

      def notification_payload: () -> untyped

      def handle_feature_flag_enabled_response: () -> untyped
    end
  end
end
