class Admin::AbuseReportsController < Admin::ApplicationController
  @abuse_reports: untyped

  @abuse_report: untyped

  def index: () -> untyped

  def show: () -> nil

  def update: () -> untyped

  def moderate_user: () -> untyped

  def destroy: () -> untyped

  private

  def find_abuse_report: () -> untyped

  def set_status_param: () -> untyped

  def permitted_params: () -> untyped

  def permitted_index_params: () -> untyped
end
