module Admin
  class BatchedJobsController < ApplicationController
    @job: untyped

    @transition_logs: untyped

    @selected_database: untyped

    def show: () -> untyped

    private

    def support_multiple_databases: () { () -> untyped } -> untyped

    def base_model: () -> untyped

    def safe_params: () -> untyped
  end
end
