class Admin::LabelsController < Admin::ApplicationController
  @labels: untyped

  @label: untyped

  def index: () -> untyped

  def show: () -> nil

  def new: () -> untyped

  def edit: () -> nil

  def create: () -> untyped

  def update: () -> untyped

  def destroy: () -> untyped

  private

  def set_label: () -> untyped

  def label_params: () -> untyped
end
