module Security
  module CiConfiguration
    class DependencyScanningBuildAction < BaseBuildAction
      private

      def update_existing_content!: () -> untyped

      def template: () -> ("Auto-DevOps.gitlab-ci.yml" | "Jobs/Dependency-Scanning.v2.gitlab-ci.yml")
    end
  end
end
